{% macro return_config_br_f_loan_proposals_br_custom() %}
{#-target_country=br;target_schema=silver;target_table_name=f_loan_proposals_br-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2022-08-23 15:54 TZ-0300",
    "is_group_feature_active": true,
    "relevant_properties": {
        "schema_country": "br",
        "files_db_table_name": "f_loan_proposals_br",
        "files_db_table_pks": [
            "loan_proposal_id"
        ]
    },
    "events": {
        "conditionalcreditcheckpassed_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassed_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassed_unnested_by_loan_proposal_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpassedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpassedwithlowerapprovedamountbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassedwithlowerapprovedamountbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "psychometricevaluationisrequiredbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckfailedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckfailedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalconditionalcreditcheckpassedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalcreditcheckfailedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalcreditcheckpassedbr_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_br",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "ally_mdf",
            "ally_mdf_cancellation",
            "ally_mdf_fraud",
            "ally_slug",
            "application_id",
            "approved_amount",
            "client_id",
            "contribution_margin",
            "decision_npv",
            "discount_rate",
            "first_loan_cash",
            "first_loan_npv",
            "first_loan_roe",
            "ia_pd_multiplier",
            "interest_rate",
            "lbl",
            "learning_population",
            "lifetime_cash",
            "lifetime_npv",
            "lifetime_roe",
            "loan_proposal_id",
            "ocurred_on",
            "returning_client",
            "term",
            "total_interest"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}