{% macro return_config_co_f_kyc_bureau_credit_history_co_logs_custom() %}
{#-target_country=co;target_schema=silver;target_table_name=f_kyc_bureau_credit_history_co_logs-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2022-11-16 20:00 TZ-0500",
    "is_group_feature_active": false,
    "relevant_properties": {
        "schema_country": "co",
        "files_db_table_name": "f_kyc_bureau_credit_history_co_logs",
        "files_db_table_pks": [
            "event_id"
        ]
    },
    "events": {
        "prospectbureaucredithistoryobtained": {
            "direct_attributes": [
                "event_id",
                "application_id",
                "client_id",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_balance",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_closedAccounts",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_creditUtilizationRatio",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_initialApprovedAmount",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_installmentAmount",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_maximumDelinquency",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_openedAccounts",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_rating",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_score",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_totalClosedAccounts",
                "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_totalOpenedAccounts",
                "commercial_commercialSummaryExperian_summary_balance_delinquent30Balance",
                "commercial_commercialSummaryExperian_summary_balance_delinquent60Balance",
                "commercial_commercialSummaryExperian_summary_balance_delinquent90Balance",
                "commercial_commercialSummaryExperian_summary_balance_delinquentBalance",
                "commercial_commercialSummaryExperian_summary_balance_higherBalance",
                "commercial_commercialSummaryExperian_summary_balance_installmentAmount",
                "commercial_commercialSummaryExperian_summary_balance_totalBalance",
                "commercial_commercialSummaryExperian_summary_principal_claims",
                "commercial_commercialSummaryExperian_summary_principal_closedAccounts",
                "commercial_commercialSummaryExperian_summary_principal_closedAccountsAHOCCB",
                "commercial_commercialSummaryExperian_summary_principal_customerSince",
                "commercial_commercialSummaryExperian_summary_principal_disagreementsToDate",
                "commercial_commercialSummaryExperian_summary_principal_lastSixMonthsQueries",
                "commercial_commercialSummaryExperian_summary_principal_negativeHistoryLastTwelveMonths",
                "commercial_commercialSummaryExperian_summary_principal_negativeOpenAccounts",
                "commercial_commercialSummaryExperian_summary_principal_openAccounts",
                "commercial_commercialSummaryExperian_summary_principal_openAccountsAHOCCB",
                "commercial_incomeEstimator_averageSMLV",
                "commercial_incomeEstimator_creditCardBalance",
                "commercial_incomeEstimator_creditCardInitialApprovedAmount",
                "commercial_incomeEstimator_creditCardInstallment",
                "commercial_incomeEstimator_estimatedIncome",
                "commercial_incomeEstimator_indebtednessCapacity",
                "commercial_incomeEstimator_maximum",
                "commercial_incomeEstimator_maximumSMLV",
                "commercial_incomeEstimator_minimum",
                "commercial_incomeEstimator_minimumSMLV",
                "commercial_incomeEstimator_nonRevolvingTotalBalance",
                "commercial_incomeEstimator_nonRevolvingTotalInitialApprovedAmount",
                "commercial_incomeEstimator_nonRevolvingTotalInstallment",
                "commercial_incomeEstimator_nonRevolvingTotalProducts",
                "commercial_incomeEstimator_paymentCapacity",
                "commercial_incomeEstimator_totalActiveCreditCards",
                "commercial_incomeEstimator_totalActiveProducts",
                "commercial_incomeEstimator_totalBalance",
                "commercial_incomeEstimator_totalInitialApprovedAmount",
                "commercial_incomeEstimator_totalInstallment",
                "commercial_incomeValidator_healthEntity",
                "commercial_incomeValidator_pensionFundName",
                "commercial_indebtednessSummary_quarter1_date",
                "commercial_indebtednessSummary_quarter1_numberOfEntities",
                "commercial_indebtednessSummary_quarter1_numberOfPurchases",
                "commercial_indebtednessSummary_quarter1_numberOfRefinanced",
                "commercial_indebtednessSummary_quarter1_numberOfWriteOffs",
                "commercial_indebtednessSummary_quarter2_date",
                "commercial_indebtednessSummary_quarter2_numberOfEntities",
                "commercial_indebtednessSummary_quarter2_numberOfPurchases",
                "commercial_indebtednessSummary_quarter2_numberOfRefinanced",
                "commercial_indebtednessSummary_quarter2_numberOfWriteOffs",
                "commercial_indebtednessSummary_quarter3_date",
                "commercial_indebtednessSummary_quarter3_numberOfEntities",
                "commercial_indebtednessSummary_quarter3_numberOfPurchases",
                "commercial_indebtednessSummary_quarter3_numberOfRefinanced",
                "commercial_indebtednessSummary_quarter3_numberOfWriteOffs",
                "commercial_provider",
                "metadata_context_traceId",
                "ocurred_on"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "application_id",
            "client_id",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_balance",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_closedAccounts",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_creditUtilizationRatio",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_initialApprovedAmount",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_installmentAmount",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_maximumDelinquency",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_openedAccounts",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_rating",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_score",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_totalClosedAccounts",
            "commercial_commercialSummaryExperian_balanceEvolution_averageAnalysis_totalOpenedAccounts",
            "commercial_commercialSummaryExperian_summary_balance_delinquent30Balance",
            "commercial_commercialSummaryExperian_summary_balance_delinquent60Balance",
            "commercial_commercialSummaryExperian_summary_balance_delinquent90Balance",
            "commercial_commercialSummaryExperian_summary_balance_delinquentBalance",
            "commercial_commercialSummaryExperian_summary_balance_higherBalance",
            "commercial_commercialSummaryExperian_summary_balance_installmentAmount",
            "commercial_commercialSummaryExperian_summary_balance_totalBalance",
            "commercial_commercialSummaryExperian_summary_principal_claims",
            "commercial_commercialSummaryExperian_summary_principal_closedAccounts",
            "commercial_commercialSummaryExperian_summary_principal_closedAccountsAHOCCB",
            "commercial_commercialSummaryExperian_summary_principal_customerSince",
            "commercial_commercialSummaryExperian_summary_principal_disagreementsToDate",
            "commercial_commercialSummaryExperian_summary_principal_lastSixMonthsQueries",
            "commercial_commercialSummaryExperian_summary_principal_negativeHistoryLastTwelveMonths",
            "commercial_commercialSummaryExperian_summary_principal_negativeOpenAccounts",
            "commercial_commercialSummaryExperian_summary_principal_openAccounts",
            "commercial_commercialSummaryExperian_summary_principal_openAccountsAHOCCB",
            "commercial_incomeEstimator_averageSMLV",
            "commercial_incomeEstimator_creditCardBalance",
            "commercial_incomeEstimator_creditCardInitialApprovedAmount",
            "commercial_incomeEstimator_creditCardInstallment",
            "commercial_incomeEstimator_estimatedIncome",
            "commercial_incomeEstimator_indebtednessCapacity",
            "commercial_incomeEstimator_maximum",
            "commercial_incomeEstimator_maximumSMLV",
            "commercial_incomeEstimator_minimum",
            "commercial_incomeEstimator_minimumSMLV",
            "commercial_incomeEstimator_nonRevolvingTotalBalance",
            "commercial_incomeEstimator_nonRevolvingTotalInitialApprovedAmount",
            "commercial_incomeEstimator_nonRevolvingTotalInstallment",
            "commercial_incomeEstimator_nonRevolvingTotalProducts",
            "commercial_incomeEstimator_paymentCapacity",
            "commercial_incomeEstimator_totalActiveCreditCards",
            "commercial_incomeEstimator_totalActiveProducts",
            "commercial_incomeEstimator_totalBalance",
            "commercial_incomeEstimator_totalInitialApprovedAmount",
            "commercial_incomeEstimator_totalInstallment",
            "commercial_incomeValidator_healthEntity",
            "commercial_incomeValidator_pensionFundName",
            "commercial_indebtednessSummary_quarter1_date",
            "commercial_indebtednessSummary_quarter1_numberOfEntities",
            "commercial_indebtednessSummary_quarter1_numberOfPurchases",
            "commercial_indebtednessSummary_quarter1_numberOfRefinanced",
            "commercial_indebtednessSummary_quarter1_numberOfWriteOffs",
            "commercial_indebtednessSummary_quarter2_date",
            "commercial_indebtednessSummary_quarter2_numberOfEntities",
            "commercial_indebtednessSummary_quarter2_numberOfPurchases",
            "commercial_indebtednessSummary_quarter2_numberOfRefinanced",
            "commercial_indebtednessSummary_quarter2_numberOfWriteOffs",
            "commercial_indebtednessSummary_quarter3_date",
            "commercial_indebtednessSummary_quarter3_numberOfEntities",
            "commercial_indebtednessSummary_quarter3_numberOfPurchases",
            "commercial_indebtednessSummary_quarter3_numberOfRefinanced",
            "commercial_indebtednessSummary_quarter3_numberOfWriteOffs",
            "commercial_provider",
            "event_id",
            "metadata_context_traceId",
            "ocurred_on"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}