{% macro return_config_br_f_kyc_telesign_phoneid_v2_br_custom() %}
{#-target_country=br;target_schema=silver;target_table_name=f_kyc_telesign_phoneid_v2_br-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2022-12-05 15:00 TZ-0500",
    "is_group_feature_active": true,
    "relevant_properties": {
        "schema_country": "br",
        "files_db_table_name": "f_kyc_telesign_phoneid_v2_br",
        "files_db_table_pks": [
            "application_id"
        ]
    },
    "events": {
        "telesignphoneidobtained_v2": {
            "direct_attributes": [
                "application_id",
                "client_id",
                "telesignPhoneId_blocklisting_blockCode",
                "telesignPhoneId_blocklisting_blockDescription",
                "telesignPhoneId_blocklisting_blocked",
                "telesignPhoneId_carrier_name",
                "telesignPhoneId_contact_addressFour",
                "telesignPhoneId_contact_addressOne",
                "telesignPhoneId_contact_addressThree",
                "telesignPhoneId_contact_addressTwo",
                "telesignPhoneId_contact_city",
                "telesignPhoneId_contact_country",
                "telesignPhoneId_contact_emailAddress",
                "telesignPhoneId_contact_firstName",
                "telesignPhoneId_contact_lastName",
                "telesignPhoneId_contact_stateProvince",
                "telesignPhoneId_contact_status_code",
                "telesignPhoneId_contact_status_description",
                "telesignPhoneId_contact_zipPostalCode",
                "telesignPhoneId_location_city",
                "telesignPhoneId_location_country_iso2",
                "telesignPhoneId_location_country_iso3",
                "telesignPhoneId_location_country_name",
                "telesignPhoneId_numbering_cleansing_call_cleansedCode",
                "telesignPhoneId_numbering_cleansing_call_countryCode",
                "telesignPhoneId_numbering_cleansing_call_maxLength",
                "telesignPhoneId_numbering_cleansing_call_minLength",
                "telesignPhoneId_numbering_cleansing_call_phoneNumber",
                "telesignPhoneId_numbering_cleansing_sms_cleansedCode",
                "telesignPhoneId_numbering_cleansing_sms_countryCode",
                "telesignPhoneId_numbering_cleansing_sms_maxLength",
                "telesignPhoneId_numbering_cleansing_sms_minLength",
                "telesignPhoneId_numbering_cleansing_sms_phoneNumber",
                "telesignPhoneId_numbering_original_completePhoneNumber",
                "telesignPhoneId_numbering_original_countryCode",
                "telesignPhoneId_numbering_original_phoneNumber",
                "telesignPhoneId_phoneType_code",
                "telesignPhoneId_phoneType_description",
                "telesignPhoneId_portingHistory_numberOfPortings",
                "telesignPhoneId_portingHistory_portingDateTime",
                "telesignPhoneId_portingHistory_status_code",
                "telesignPhoneId_portingHistory_status_description",
                "telesignPhoneId_referenceId",
                "telesignPhoneId_simSwap_riskIndicator",
                "telesignPhoneId_simSwap_status_code",
                "telesignPhoneId_simSwap_status_description",
                "telesignPhoneId_status_code",
                "telesignPhoneId_status_description",
                "telesignPhoneId_status_updatedOn",
                "telesignPhoneId_subscriberStatus_accountActivationDate",
                "telesignPhoneId_subscriberStatus_accountStatus",
                "telesignPhoneId_subscriberStatus_accountTenureMax",
                "telesignPhoneId_subscriberStatus_accountTenureMin",
                "telesignPhoneId_subscriberStatus_contractType",
                "telesignPhoneId_subscriberStatus_status_code",
                "telesignPhoneId_subscriberStatus_status_description",
                "metadata_context_traceId",
                "ocurred_on"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "application_id",
            "client_id",
            "metadata_context_traceId",
            "ocurred_on",
            "telesignPhoneId_blocklisting_blockCode",
            "telesignPhoneId_blocklisting_blockDescription",
            "telesignPhoneId_blocklisting_blocked",
            "telesignPhoneId_carrier_name",
            "telesignPhoneId_contact_addressFour",
            "telesignPhoneId_contact_addressOne",
            "telesignPhoneId_contact_addressThree",
            "telesignPhoneId_contact_addressTwo",
            "telesignPhoneId_contact_city",
            "telesignPhoneId_contact_country",
            "telesignPhoneId_contact_emailAddress",
            "telesignPhoneId_contact_firstName",
            "telesignPhoneId_contact_lastName",
            "telesignPhoneId_contact_stateProvince",
            "telesignPhoneId_contact_status_code",
            "telesignPhoneId_contact_status_description",
            "telesignPhoneId_contact_zipPostalCode",
            "telesignPhoneId_location_city",
            "telesignPhoneId_location_country_iso2",
            "telesignPhoneId_location_country_iso3",
            "telesignPhoneId_location_country_name",
            "telesignPhoneId_numbering_cleansing_call_cleansedCode",
            "telesignPhoneId_numbering_cleansing_call_countryCode",
            "telesignPhoneId_numbering_cleansing_call_maxLength",
            "telesignPhoneId_numbering_cleansing_call_minLength",
            "telesignPhoneId_numbering_cleansing_call_phoneNumber",
            "telesignPhoneId_numbering_cleansing_sms_cleansedCode",
            "telesignPhoneId_numbering_cleansing_sms_countryCode",
            "telesignPhoneId_numbering_cleansing_sms_maxLength",
            "telesignPhoneId_numbering_cleansing_sms_minLength",
            "telesignPhoneId_numbering_cleansing_sms_phoneNumber",
            "telesignPhoneId_numbering_original_completePhoneNumber",
            "telesignPhoneId_numbering_original_countryCode",
            "telesignPhoneId_numbering_original_phoneNumber",
            "telesignPhoneId_phoneType_code",
            "telesignPhoneId_phoneType_description",
            "telesignPhoneId_portingHistory_numberOfPortings",
            "telesignPhoneId_portingHistory_portingDateTime",
            "telesignPhoneId_portingHistory_status_code",
            "telesignPhoneId_portingHistory_status_description",
            "telesignPhoneId_referenceId",
            "telesignPhoneId_simSwap_riskIndicator",
            "telesignPhoneId_simSwap_status_code",
            "telesignPhoneId_simSwap_status_description",
            "telesignPhoneId_status_code",
            "telesignPhoneId_status_description",
            "telesignPhoneId_status_updatedOn",
            "telesignPhoneId_subscriberStatus_accountActivationDate",
            "telesignPhoneId_subscriberStatus_accountStatus",
            "telesignPhoneId_subscriberStatus_accountTenureMax",
            "telesignPhoneId_subscriberStatus_accountTenureMin",
            "telesignPhoneId_subscriberStatus_contractType",
            "telesignPhoneId_subscriberStatus_status_code",
            "telesignPhoneId_subscriberStatus_status_description"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}