{% macro return_config_co_f_kyc_telesign_phoneid_v1v2_co_logs_custom() %}
{#-target_country=co;target_schema=silver;target_table_name=f_kyc_telesign_phoneid_v1v2_co_logs-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2022-12-05 15:00 TZ-0500",
    "is_group_feature_active": false,
    "relevant_properties": {
        "schema_country": "co",
        "files_db_table_name": "f_kyc_telesign_phoneid_v1v2_co_logs",
        "files_db_table_pks": [
            "event_id"
        ]
    },
    "events": {
        "telesignphoneidobtained": {
            "direct_attributes": [
                "event_id",
                "application_id",
                "client_id",
                "telesignPhoneId_blocklisting_blockCode",
                "telesignPhoneId_blocklisting_blockDescription",
                "telesignPhoneId_blocklisting_blocked",
                "telesignPhoneId_carrier_name",
                "telesignPhoneId_location_city",
                "telesignPhoneId_location_country_iso2",
                "telesignPhoneId_location_country_iso3",
                "telesignPhoneId_location_country_name",
                "telesignPhoneId_numbering_cleansing_call_cleansedCode",
                "telesignPhoneId_numbering_cleansing_call_countryCode",
                "telesignPhoneId_numbering_cleansing_call_maxLength",
                "telesignPhoneId_numbering_cleansing_call_minLength",
                "telesignPhoneId_numbering_cleansing_call_phoneNumber",
                "telesignPhoneId_numbering_cleansing_sms_cleansedCode",
                "telesignPhoneId_numbering_cleansing_sms_countryCode",
                "telesignPhoneId_numbering_cleansing_sms_maxLength",
                "telesignPhoneId_numbering_cleansing_sms_minLength",
                "telesignPhoneId_numbering_cleansing_sms_phoneNumber",
                "telesignPhoneId_numbering_original_completePhoneNumber",
                "telesignPhoneId_numbering_original_countryCode",
                "telesignPhoneId_numbering_original_phoneNumber",
                "telesignPhoneId_phoneType_code",
                "telesignPhoneId_phoneType_description",
                "telesignPhoneId_portingHistory_numberOfPortings",
                "telesignPhoneId_portingHistory_portingDateTime",
                "telesignPhoneId_portingHistory_status_code",
                "telesignPhoneId_portingHistory_status_description",
                "telesignPhoneId_referenceId",
                "telesignPhoneId_simSwap_riskIndicator",
                "telesignPhoneId_simSwap_status_code",
                "telesignPhoneId_simSwap_status_description",
                "telesignPhoneId_simSwap_swapDateTime",
                "telesignPhoneId_status_code",
                "telesignPhoneId_status_description",
                "telesignPhoneId_status_updatedOn",
                "metadata_context_traceId",
                "custom_kyc_event_version",
                "ocurred_on"
            ],
            "custom_attributes": {}
        },
        "telesignphoneidobtained_v2": {
            "direct_attributes": [
                "event_id",
                "application_id",
                "client_id",
                "telesignPhoneId_blocklisting_blockCode",
                "telesignPhoneId_blocklisting_blockDescription",
                "telesignPhoneId_blocklisting_blocked",
                "telesignPhoneId_carrier_name",
                "telesignPhoneId_location_city",
                "telesignPhoneId_location_country_iso2",
                "telesignPhoneId_location_country_iso3",
                "telesignPhoneId_location_country_name",
                "telesignPhoneId_numbering_cleansing_call_cleansedCode",
                "telesignPhoneId_numbering_cleansing_call_countryCode",
                "telesignPhoneId_numbering_cleansing_call_maxLength",
                "telesignPhoneId_numbering_cleansing_call_minLength",
                "telesignPhoneId_numbering_cleansing_call_phoneNumber",
                "telesignPhoneId_numbering_cleansing_sms_cleansedCode",
                "telesignPhoneId_numbering_cleansing_sms_countryCode",
                "telesignPhoneId_numbering_cleansing_sms_maxLength",
                "telesignPhoneId_numbering_cleansing_sms_minLength",
                "telesignPhoneId_numbering_cleansing_sms_phoneNumber",
                "telesignPhoneId_numbering_original_completePhoneNumber",
                "telesignPhoneId_numbering_original_countryCode",
                "telesignPhoneId_numbering_original_phoneNumber",
                "telesignPhoneId_phoneType_code",
                "telesignPhoneId_phoneType_description",
                "telesignPhoneId_portingHistory_numberOfPortings",
                "telesignPhoneId_portingHistory_portingDateTime",
                "telesignPhoneId_portingHistory_status_code",
                "telesignPhoneId_portingHistory_status_description",
                "telesignPhoneId_referenceId",
                "telesignPhoneId_simSwap_riskIndicator",
                "telesignPhoneId_simSwap_status_code",
                "telesignPhoneId_simSwap_status_description",
                "telesignPhoneId_simSwap_swapDateTime",
                "telesignPhoneId_status_code",
                "telesignPhoneId_status_description",
                "telesignPhoneId_status_updatedOn",
                "metadata_context_traceId",
                "custom_kyc_event_version",
                "ocurred_on"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "application_id",
            "client_id",
            "custom_kyc_event_version",
            "event_id",
            "metadata_context_traceId",
            "ocurred_on",
            "telesignPhoneId_blocklisting_blockCode",
            "telesignPhoneId_blocklisting_blockDescription",
            "telesignPhoneId_blocklisting_blocked",
            "telesignPhoneId_carrier_name",
            "telesignPhoneId_location_city",
            "telesignPhoneId_location_country_iso2",
            "telesignPhoneId_location_country_iso3",
            "telesignPhoneId_location_country_name",
            "telesignPhoneId_numbering_cleansing_call_cleansedCode",
            "telesignPhoneId_numbering_cleansing_call_countryCode",
            "telesignPhoneId_numbering_cleansing_call_maxLength",
            "telesignPhoneId_numbering_cleansing_call_minLength",
            "telesignPhoneId_numbering_cleansing_call_phoneNumber",
            "telesignPhoneId_numbering_cleansing_sms_cleansedCode",
            "telesignPhoneId_numbering_cleansing_sms_countryCode",
            "telesignPhoneId_numbering_cleansing_sms_maxLength",
            "telesignPhoneId_numbering_cleansing_sms_minLength",
            "telesignPhoneId_numbering_cleansing_sms_phoneNumber",
            "telesignPhoneId_numbering_original_completePhoneNumber",
            "telesignPhoneId_numbering_original_countryCode",
            "telesignPhoneId_numbering_original_phoneNumber",
            "telesignPhoneId_phoneType_code",
            "telesignPhoneId_phoneType_description",
            "telesignPhoneId_portingHistory_numberOfPortings",
            "telesignPhoneId_portingHistory_portingDateTime",
            "telesignPhoneId_portingHistory_status_code",
            "telesignPhoneId_portingHistory_status_description",
            "telesignPhoneId_referenceId",
            "telesignPhoneId_simSwap_riskIndicator",
            "telesignPhoneId_simSwap_status_code",
            "telesignPhoneId_simSwap_status_description",
            "telesignPhoneId_simSwap_swapDateTime",
            "telesignPhoneId_status_code",
            "telesignPhoneId_status_description",
            "telesignPhoneId_status_updatedOn"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}