{% macro return_config_co_f_kyc_bureau_credit_history_tradelines_co_logs_custom() %}
{#-target_country=co;target_schema=silver;target_table_name=f_kyc_bureau_credit_history_tradelines_co_logs-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2022-11-16 20:00 TZ-0500",
    "is_group_feature_active": false,
    "relevant_properties": {
        "schema_country": "co",
        "files_db_table_name": "f_kyc_bureau_credit_history_tradelines_co_logs",
        "files_db_table_pks": [
            "surrogate_key"
        ]
    },
    "events": {
        "prospectbureaucredithistoryobtained_unnested_by_tradeline": {
            "direct_attributes": [
                "surrogate_key",
                "item_pseudo_idx",
                "event_id",
                "application_id",
                "client_id",
                "array_parent_path",
                "bureau_tradeline_pastMonthlyBehaviours",
                "bureau_tradeline_balance",
                "bureau_tradeline_balanceShare",
                "bureau_tradeline_branch",
                "bureau_tradeline_city",
                "bureau_tradeline_clauseNumberMonths",
                "bureau_tradeline_contractNumberMonths",
                "bureau_tradeline_contractType",
                "bureau_tradeline_creditCardClass",
                "bureau_tradeline_creditLineType",
                "bureau_tradeline_creditType",
                "bureau_tradeline_currency",
                "bureau_tradeline_debtorStatus",
                "bureau_tradeline_debtorType",
                "bureau_tradeline_delinquencyLikelihood",
                "bureau_tradeline_entityName",
                "bureau_tradeline_entityType",
                "bureau_tradeline_extinctionPaymentMode",
                "bureau_tradeline_franchise",
                "bureau_tradeline_initialApprovedAmount",
                "bureau_tradeline_installmentAmount",
                "bureau_tradeline_installmentsPaid",
                "bureau_tradeline_lastUpdateDate",
                "bureau_tradeline_maxDaysPastDue",
                "bureau_tradeline_minMonthsClause",
                "bureau_tradeline_negativeInfoVisibleUntil",
                "bureau_tradeline_numberAgreedInstallments",
                "bureau_tradeline_numberInstallmentsPastDue",
                "bureau_tradeline_obligationNumber",
                "bureau_tradeline_obligationStatus",
                "bureau_tradeline_obligationStatusLastUpdateDate",
                "bureau_tradeline_obligationType",
                "bureau_tradeline_originationDate",
                "bureau_tradeline_originationEntityName",
                "bureau_tradeline_pastDueAmount",
                "bureau_tradeline_pastMonthlyBehaviour",
                "bureau_tradeline_paymentDate",
                "bureau_tradeline_paymentStatus",
                "bureau_tradeline_paymentStatusLastUpdateDate",
                "bureau_tradeline_paymentType",
                "bureau_tradeline_periodicity",
                "bureau_tradeline_plasticStatus",
                "bureau_tradeline_plasticStatusLastUpdateDate",
                "bureau_tradeline_rating",
                "bureau_tradeline_refinanceType",
                "bureau_tradeline_refinanced",
                "bureau_tradeline_refinancedDate",
                "bureau_tradeline_returnedChecks",
                "bureau_tradeline_terminationDate",
                "bureau_tradeline_timesRefinanced",
                "bureau_tradeline_validity",
                "bureau_tradeline_warrantyCoverage",
                "bureau_tradeline_warrantyType",
                "ocurred_on"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "application_id",
            "array_parent_path",
            "bureau_tradeline_balance",
            "bureau_tradeline_balanceShare",
            "bureau_tradeline_branch",
            "bureau_tradeline_city",
            "bureau_tradeline_clauseNumberMonths",
            "bureau_tradeline_contractNumberMonths",
            "bureau_tradeline_contractType",
            "bureau_tradeline_creditCardClass",
            "bureau_tradeline_creditLineType",
            "bureau_tradeline_creditType",
            "bureau_tradeline_currency",
            "bureau_tradeline_debtorStatus",
            "bureau_tradeline_debtorType",
            "bureau_tradeline_delinquencyLikelihood",
            "bureau_tradeline_entityName",
            "bureau_tradeline_entityType",
            "bureau_tradeline_extinctionPaymentMode",
            "bureau_tradeline_franchise",
            "bureau_tradeline_initialApprovedAmount",
            "bureau_tradeline_installmentAmount",
            "bureau_tradeline_installmentsPaid",
            "bureau_tradeline_lastUpdateDate",
            "bureau_tradeline_maxDaysPastDue",
            "bureau_tradeline_minMonthsClause",
            "bureau_tradeline_negativeInfoVisibleUntil",
            "bureau_tradeline_numberAgreedInstallments",
            "bureau_tradeline_numberInstallmentsPastDue",
            "bureau_tradeline_obligationNumber",
            "bureau_tradeline_obligationStatus",
            "bureau_tradeline_obligationStatusLastUpdateDate",
            "bureau_tradeline_obligationType",
            "bureau_tradeline_originationDate",
            "bureau_tradeline_originationEntityName",
            "bureau_tradeline_pastDueAmount",
            "bureau_tradeline_pastMonthlyBehaviour",
            "bureau_tradeline_pastMonthlyBehaviours",
            "bureau_tradeline_paymentDate",
            "bureau_tradeline_paymentStatus",
            "bureau_tradeline_paymentStatusLastUpdateDate",
            "bureau_tradeline_paymentType",
            "bureau_tradeline_periodicity",
            "bureau_tradeline_plasticStatus",
            "bureau_tradeline_plasticStatusLastUpdateDate",
            "bureau_tradeline_rating",
            "bureau_tradeline_refinanceType",
            "bureau_tradeline_refinanced",
            "bureau_tradeline_refinancedDate",
            "bureau_tradeline_returnedChecks",
            "bureau_tradeline_terminationDate",
            "bureau_tradeline_timesRefinanced",
            "bureau_tradeline_validity",
            "bureau_tradeline_warrantyCoverage",
            "bureau_tradeline_warrantyType",
            "client_id",
            "event_id",
            "item_pseudo_idx",
            "ocurred_on",
            "surrogate_key"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}