{% macro return_config_co_f_loan_proposals_co_custom() %}
{#-target_country=co;target_schema=silver;target_table_name=f_loan_proposals_co-#}
{%- set configuration_dict = {
    "config_parser_execution_date": "2024-05-07 10:18 TZ-0300",
    "is_group_feature_active": true,
    "relevant_properties": {
        "schema_country": "co",
        "files_db_table_name": "f_loan_proposals_co",
        "files_db_table_pks": [
            "loan_proposal_id"
        ]
    },
    "events": {
        "conditionalcreditcheckpassed_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassed_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassed_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpassedwithlowerapprovedamount_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassedwithlowerapprovedamount_unnested_by_loan_proposals_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassedwithinsufficientaddicupo_unnested_by_loan_proposal_event": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "AllyApplicationUpdated": {
            "stage": "legacy_or_non_origination",
            "direct_attributes": [
                "loan_proposal_id",
                "application_id",
                "client_id",
                "ally_slug",
                "ocurred_on"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "psychometricevaluationisrequiredco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalcreditcheckpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalconditionalcreditcheckpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckapprovedsantanderco_unnested_by_loan_proposals_event": {
            "stage": "risk_evaluation_santander_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "loan_subvention_applied",
                "loan_subvention_value",
                "loan_subvention_iva",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckfailedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpsychometricpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_psychometric_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "FirstPaymentDateChangedCO": {
            "stage": "loan_proposals_co",
            "direct_attributes": [
                "loan_proposal_id",
                "ocurred_on",
                "first_payment_date",
                "returning_client"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpsychometricpassedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_psychometric_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "creditcheckpsychometricfailedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_psychometric_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckfailedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "preapprovalcreditcheckfailedco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_preapproval_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "conditionalcreditcheckpassedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest",
                "guarantee_provider"
            ],
            "custom_attributes": {}
        },
        "creditcheckfailedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest",
                "guarantee_provider"
            ],
            "custom_attributes": {}
        },
        "creditcheckpassedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest",
                "guarantee_provider"
            ],
            "custom_attributes": {}
        },
        "psychometricevaluationisrequiredpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "total_fga_rate",
                "fga_tax_rate",
                "fga_comission_rate",
                "fga_client_rate",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckfailedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "fga_client_rate",
                "total_fga_rate",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest",
                "guarantee_provider"
            ],
            "custom_attributes": {}
        },
        "clientcreditcheckpassedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "fga_client_rate",
                "total_fga_rate",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest"
            ],
            "custom_attributes": {}
        },
        "conditionalclientcreditcheckpassedpagoco_unnested_by_loan_proposals_event": {
            "stage": "underwriting_rc_pago_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_mdf",
                "ally_mdf_cancellation",
                "ally_mdf_fraud",
                "ally_slug",
                "interest_rate",
                "returning_client",
                "lbl",
                "learning_population",
                "decision_npv",
                "first_loan_npv",
                "lifetime_npv",
                "discount_rate",
                "first_loan_roe",
                "first_loan_cash",
                "fga_client_rate",
                "total_fga_rate",
                "lifetime_roe",
                "lifetime_cash",
                "contribution_margin",
                "approved_amount",
                "ia_pd_multiplier",
                "total_interest",
                "guarantee_provider"
            ],
            "custom_attributes": {}
        },
        "loanrefinanceproposalscreatedco_unnested_by_loan_proposal": {
            "stage": "refinance_loan_proposals_co",
            "direct_attributes": [
                "loan_proposal_id",
                "client_id",
                "application_id",
                "ocurred_on",
                "term",
                "ally_slug",
                "interest_rate",
                "fga_client_rate",
                "total_fga_rate",
                "approved_amount",
                "total_interest"
            ],
            "custom_attributes": {}
        }
    },
    "unique_db_fields": {
        "direct": [
            "ally_mdf",
            "ally_mdf_cancellation",
            "ally_mdf_fraud",
            "ally_slug",
            "application_id",
            "approved_amount",
            "client_id",
            "contribution_margin",
            "decision_npv",
            "discount_rate",
            "fga_client_rate",
            "fga_comission_rate",
            "fga_tax_rate",
            "first_loan_cash",
            "first_loan_npv",
            "first_loan_roe",
            "first_payment_date",
            "guarantee_provider",
            "ia_pd_multiplier",
            "interest_rate",
            "lbl",
            "learning_population",
            "lifetime_cash",
            "lifetime_npv",
            "lifetime_roe",
            "loan_proposal_id",
            "loan_subvention_applied",
            "loan_subvention_iva",
            "loan_subvention_value",
            "ocurred_on",
            "returning_client",
            "term",
            "total_fga_rate",
            "total_interest"
        ],
        "custom": []
    }
}
-%}
{{ return(configuration_dict) }}
{% endmacro %}