{#- DOCS -#}
{#- @ 2023-02-16 by Carlos D.A. Puerto Niño - Analytics Engineer -#}
{#- Description: Macro to build an unified final query based on previously prepared queries using `gold_metric_by_calendar_periods_block_builder` macro -#}
{#- Usage: 
    SELECT
     {{gold_metric_by_calendar_periods_block_unifier(extra_columns = ['numerical_target_column','string_column'})}}

    FROM consolidated_results AS r
    LEFT JOIN (SELECT * FROM gold.dm_support_today_master_calendar ARRAYS_OVERLAP(countries,ARRAY('UTC'))) AS d ON TRUE
-#}
{#- r = results_cte_alias -#}
{#- d = calendar_table_alias -#}
{% macro gold_metric_by_calendar_periods_block_unifier(
    extra_columns = [],
    r = 'r',
    d = 'd') %}
{#- -#}-- AUTOGENERATED CODE START
-- TODAY
{{d}}.today,
-- GENERAL METRIC REFERENCE
{{r}}.metric,
{{r}}.metric_type,
{{r}}.numerator_name,
{{r}}.denominator_name,
{{r}}.positive_change_is_good,
{{r}}.ordered,
-- ADDITIONAL COLUMNS
{%- for column_name in extra_columns %}
{{r}}.{{column_name}},
{%- endfor %}
-- METRIC CALCULATIONS
{{r}}.yesterday_num                 / NULLIF({{r}}.yesterday_den,0)                 AS yesterday_complete,
{{r}}.wtd_num                       / NULLIF({{r}}.wtd_den,0)                       AS wtd,
{{r}}.mtd_num                       / NULLIF({{r}}.mtd_den,0)                       AS mtd,
{{r}}.qtd_num                       / NULLIF({{r}}.qtd_den,0)                       AS qtd,
{{r}}.last_week_complete_num        / NULLIF({{r}}.last_week_complete_den,0)        AS last_week_complete,
{{r}}.last_last_week_complete_num   / NULLIF({{r}}.last_last_week_complete_den,0)   AS last_last_week_complete,
{{r}}.3_weeks_ago_complete_num      / NULLIF({{r}}.3_weeks_ago_complete_den,0)      AS 3_weeks_ago_complete,
{{r}}.last_month_complete_num       / NULLIF({{r}}.last_month_complete_den,0)       AS last_month_complete,
{{r}}.last_week_equivalent_num      / NULLIF({{r}}.last_week_equivalent_den,0)      AS last_week_equivalent,
{{r}}.last_last_week_equivalent_num / NULLIF({{r}}.last_last_week_equivalent_den,0) AS last_last_week_equivalent,
{{r}}.last_month_equivalent_num     / NULLIF({{r}}.last_month_equivalent_den,0)     AS last_month_equivalent,
-- METRIC CALCULATIONS - DIFFERENCE OVER LAST PERIOD
CASE WHEN {{r}}.metric_type = 'percentage' THEN 'pp.' ELSE  '%' END AS period_over_period_unit,
CASE WHEN {{r}}.metric_type = 'percentage'
    THEN  ({{r}}.wtd_num                     / NULLIF({{r}}.wtd_den,0))                     -       ({{r}}.last_week_equivalent_num    / NULLIF({{r}}.last_week_equivalent_den,0))      -- percentage, pp
    ELSE (({{r}}.wtd_num                     / NULLIF({{r}}.wtd_den,0))                     / NULLIF({{r}}.last_week_equivalent_num    / NULLIF({{r}}.last_week_equivalent_den,0),0))-1 -- numeric,money; %
END AS wow_equivalent,
CASE WHEN {{r}}.metric_type = 'percentage'
    THEN  ({{r}}.last_week_complete_num      / NULLIF({{r}}.last_week_complete_den,0))      -       ({{r}}.last_last_week_complete_num / NULLIF({{r}}.last_last_week_complete_den,0))      -- percentage, pp
    ELSE (({{r}}.last_week_complete_num      / NULLIF({{r}}.last_week_complete_den,0))      / NULLIF({{r}}.last_last_week_complete_num / NULLIF({{r}}.last_last_week_complete_den,0),0))-1 -- numeric,money; %
END AS lw_o_llw_complete,
CASE WHEN {{r}}.metric_type = 'percentage'
    THEN  ({{r}}.last_last_week_complete_num / NULLIF({{r}}.last_last_week_complete_den,0)) -       ({{r}}.3_weeks_ago_complete_num    / NULLIF({{r}}.3_weeks_ago_complete_den,0))      -- percentage, pp
    ELSE (({{r}}.last_last_week_complete_num / NULLIF({{r}}.last_last_week_complete_den,0)) / NULLIF({{r}}.3_weeks_ago_complete_num    / NULLIF({{r}}.3_weeks_ago_complete_den,0),0))-1 -- numeric,money; %
END AS llw_o_3wa_complete,
CASE WHEN {{r}}.metric_type = 'percentage'
    THEN  ({{r}}.mtd_num                     / NULLIF({{r}}.mtd_den,0))                     -       ({{r}}.last_month_equivalent_num   / NULLIF({{r}}.last_month_equivalent_den,0))      -- percentage, pp
    ELSE (({{r}}.mtd_num                     / NULLIF({{r}}.mtd_den,0))                     / NULLIF({{r}}.last_month_equivalent_num   / NULLIF({{r}}.last_month_equivalent_den,0),0))-1 -- numeric,money; %
END AS mom_equivalent,
-- METRIC DETAILS - NUMERATORS AND DENOMINATORS
{{r}}.yesterday_num,
{{r}}.yesterday_den,
{{r}}.wtd_num,
{{r}}.wtd_den,
{{r}}.mtd_num,
{{r}}.mtd_den,
{{r}}.qtd_num,
{{r}}.qtd_den,
{{r}}.last_week_complete_num,
{{r}}.last_week_complete_den,
{{r}}.last_last_week_complete_num,
{{r}}.last_last_week_complete_den,
{{r}}.3_weeks_ago_complete_num,
{{r}}.3_weeks_ago_complete_den,
{{r}}.last_month_complete_num,
{{r}}.last_month_complete_den,
{{r}}.last_week_equivalent_num,
{{r}}.last_week_equivalent_den,
{{r}}.last_last_week_equivalent_num,
{{r}}.last_last_week_equivalent_den,
{{r}}.last_month_equivalent_num,
{{r}}.last_month_equivalent_den,
-- CALCULATION TIMEFRAMES AS STRING
CASE WHEN {{d}}.dow_iso = 1 THEN NULL ELSE CONCAT({{d}}.current_week_start,'-',{{d}}.yesterday)                       END AS wtd_timeframe,
CASE WHEN {{d}}.dom = 1     THEN NULL ELSE CONCAT({{d}}.current_month_start,'-',{{d}}.yesterday)                      END AS mtd_timeframe,
CASE WHEN {{d}}.doq = 1     THEN NULL ELSE CONCAT({{d}}.current_quarter_start,'-',{{d}}.yesterday)                    END AS qtd_timeframe,
                                           CONCAT({{d}}.last_week_start,'-',{{d}}.last_week_end)                          AS last_week_complete_timeframe,
                                           CONCAT({{d}}.last_last_week_start,'-',{{d}}.last_last_week_end)                AS last_last_week_complete_timeframe,
                                           CONCAT({{d}}.3_weeks_ago_start,'-',{{d}}.3_weeks_ago_end)                      AS 3_weeks_ago_complete_timeframe,
                                           CONCAT({{d}}.last_month_start,'-',{{d}}.last_month_end)                        AS last_month_complete_timeframe,
CASE WHEN {{d}}.dow_iso = 1 THEN NULL ELSE CONCAT({{d}}.last_week_start,'-',{{d}}.last_week_end_equivalent)           END AS last_week_equivalent_timeframe,
CASE WHEN {{d}}.dow_iso = 1 THEN NULL ELSE CONCAT({{d}}.last_last_week_start,'-',{{d}}.last_last_week_end_equivalent) END AS last_last_week_equivalent_timeframe,
CASE WHEN {{d}}.dom = 1     THEN NULL ELSE CONCAT({{d}}.last_month_start,'-',{{d}}.last_month_end_equivalent)         END AS last_month_equivalent_timeframe,
-- REFERENCES DATES TO TODAY
{{d}}.yesterday,
{{d}}.current_quarter_start,
{{d}}.current_month_start,
{{d}}.current_week_start,
{{d}}.`4_weeks_ago_start`,
{{d}}.`4_weeks_ago_end`,
{{d}}.`3_weeks_ago_start`,
{{d}}.`3_weeks_ago_end`,
{{d}}.last_last_week_start,
{{d}}.last_last_week_end,
{{d}}.last_week_start,
{{d}}.last_week_end,
{{d}}.last_week_end_equivalent,
{{d}}.last_last_week_end_equivalent,
{{d}}.last_month_start,
{{d}}.last_month_end,
{{d}}.last_month_end_equivalent,
{{d}}.dow_iso,
{{d}}.dom,
{{d}}.last_quarter_start,
{{d}}.last_quarter_end,
{{d}}.last_last_quarter_start,
{{d}}.last_last_quarter_end,
{{d}}.last_last_month_start,
{{d}}.last_last_month_end
/* DEBUGGING
 extra_column_and_values = {{extra_column_and_values}} ; r = {{r}} ; d = {{d}} 
 */
-- AUTOGENERATED CODE END

{% endmacro %}