addi:
  outputs:
    default:
      type: databricks
      catalog: addi_prod
      schema: dbt
      host: "{{ env_var('DATABRICKS_HOST_CLASSIC_WAREHOUSE') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_CLASSIC_WAREHOUSE') }}"
      token: "{{ env_var('DATABRICKS_PERSONAL_ACCESS_TOKEN_CLASSIC_WAREHOUSE') }}"
      connect_retries: 5
      connect_timeout: 60
      threads: 48

    databricks_classic_warehouse:
      type: databricks
      catalog: addi_prod
      schema: dbt
      host: "{{ env_var('DATABRICKS_HOST_CLASSIC_WAREHOUSE') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_CLASSIC_WAREHOUSE') }}"
      token: "{{ env_var('DATABRICKS_PERSONAL_ACCESS_TOKEN_CLASSIC_WAREHOUSE') }}"
      connect_retries: 5
      connect_timeout: 60
      threads: 48
