{{
    config(
        materialized='incremental',
        unique_key='conversation_id',
        incremental_strategy='merge',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

--Volume: 58708281 by 2023-09-19
--bronze.kustomer_conversations
SELECT
    -- MANDATORY FIELDS
    -- MAPPED FIELDS - DIRECT ATTRIBUTES
    conversation_id,
    name,
    preview,
    channels,
    status,
    message_count,
    note_count,
    satisfaction,
    satisfaction_lvl_channel,
    satisfaction_lvl_status,
    satisfaction_lvl_scheduled_for,
    satisfaction_lvl_created_at,
    satisfaction_lvl_sent_at,
    satisfaction_lvl_sent_by,
    satisfaction_lvl_rating,
    satisfaction_lvl_score,
    satisfaction_lvl_first_answer,
    created_at,
    updated_at,
    modified_at,
    last_activity_at,
    last_message_at,
    imported_at,
    spam,
    ended,
    ended_at,
    ended_reason,
    ended_by_type,
    tags,
    suggested_tags,
    predictions,
    sentiment,
    assigned_users,
    assigned_teams,
    first_message_in_message_id,
    first_message_in_sent_at,
    first_message_in_created_at,
    first_message_in_direction_type,
    first_message_in_channel,
    first_message_out_message_id,
    first_message_out_sent_at,
    first_message_out_created_at,
    first_message_out_direction_type,
    first_message_out_channel,
    first_message_out_created_by,
    last_message_in_message_id,
    last_message_in_sent_at,
    last_message_in_created_at,
    last_message_out_message_id,
    last_message_out_sent_at,
    last_message_out_created_at,
    first_response_id,
    first_response_business_time,
    first_response_created_at,
    first_response_created_by,
    first_response_sent_at,
    first_response_response_time,
    last_response_id,
    last_response_business_time,
    last_response_created_at,
    last_response_created_by,
    first_done_created_by_teams,
    first_done_assigned_teams,
    first_done_assigned_users,
    first_done_business_time,
    first_done_created_at,
    first_done_created_by,
    first_done_last_message_direction,
    first_done_last_message_direction_type,
    last_done_created_by_teams,
    last_done_assigned_teams,
    last_done_assigned_users,
    last_done_business_time,
    last_done_created_at,
    last_done_created_by,
    last_done_last_message_direction,
    last_done_last_message_direction_type,
    done_count,
    snooze_count,
    reopen_count,
    direction,
    last_message_direction,
    outbound_message_count,
    inbound_message_count,
    rev,
    priority,
    external_queue,
    total_snooze_business_time,
    total_done_business_time,
    total_open_business_time,
    total_open_business_time_since_last_done,
    merged_target,
    sla_name,
    sla_version,
    sla_matched_at,
    sla_breached,
    sla_status,
    sla_first_breach_at,
    sla_satisfied_at,
    org_id,
    customer_id,
    ended_by_id,
    queue_id,
    sla_id,
    reference_date,
    reference_date_year,
    reference_date_month,
    modification_history_name_at,
    modification_history_priority_at,
    modification_history_channel_at,
    modification_history_assigned_teams_at,
    modification_history_assigned_users_at,
    modification_history_brand_at,
    modification_history_default_lang_at,
    modification_history_status_at,
    modification_history_tags_at,
    modification_history_custom_at,
    -- CUSTOM ATTRIBUTES
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS data_platform_updated_at
-- DBT SOURCE REFERENCE
FROM {{ ref('kustomer_conversations') }}
-- DBT INCREMENTAL SENTENCE

{% if is_incremental() %}
    WHERE to_date(updated_at) BETWEEN (to_date("{{ var('start_date') }}"- INTERVAL "{{var('incremental_slack_time_in_days')}}" DAY)) AND to_date("{{ var('end_date') }}")
    AND CAST(updated_at AS TIMESTAMP) BETWEEN (to_timestamp("{{ var('start_date') }}"- INTERVAL "{{var('incremental_slack_time_in_days')}}" DAY)) AND to_timestamp("{{ var('end_date')}}")
{% endif %}