{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

--raw.snc_client_loan_calculations_co
SELECT
    -- DIRECT MODELING FIELDS
	cast(null as varchar(50)) AS id,
	applicable_rate,
	approved_amount,
	calculation_date,
	cancellation_reason,
	client_full_payment,
	client_id,
	client_min_payment,
	current_interest_covered_this_month,
	current_interest_covered_this_period,
	current_interest_due_this_period,
	current_positive_balance,
	current_principal_covered_this_month,
	current_principal_covered_this_period,
	current_principal_due_this_period,
	days_past_due,
	effective_annual_rate,
	cast(null as decimal(19,4)) AS expected_chargeoff_rate,
	first_payment_date,
	full_payment,
	initial_installment_amount,
	interest_on_overdue_principal,
	cast(null as decimal(19,2)) AS interest_on_overdue_principal_covered_this_period,
	interest_overdue,
	interest_overdue_covered_this_month,
	interest_overdue_covered_this_period,
	ipmt,
	is_cancelled,
	is_full_payment,
	is_fully_paid,
	is_fully_paid_in_old_loan_tape,
	loan_id,
	min_payment,
	cast(null as decimal(19,2)) AS monthly_positive_balance,
	months_on_books,
	origination_date,
	paid_installments,
	cast (payday as date),
	positive_balance,
	ppmt,
	prepayment_this_period,
	principal_overdue,
	principal_overdue_covered_this_month,
	principal_overdue_covered_this_period,
	term,
	total_interest_paid,
	total_applied_payment,
	total_principal_paid,
	unpaid_interest,
	unpaid_principal,
	unpaid_principal_covered_this_month,
	vintage,
	client_total_payment,
	period_prepayment_benefit,
	total_prepayment_benefit,
	current_installment_amount,
	accrued_interest_this_month,
	loan_ownership,
	prepayment_benefit_this_month,
	client_total_payment_addi,
	client_total_payment_pa,
	condoned_interest_this_month,
	interest_on_overdue_principal_covered_this_month,
	cast(client_payday as date),
	client_delinquency_balance,
	total_moratory_interest_condoned,
	total_interest_overdue_condoned,
	total_principal_overdue_condoned,
	total_current_interest_condoned,
	total_current_principal_condoned,
	total_unpaid_principal_condoned,
	interest_condoned_in_first_period,
	low_balance_loan,
	guarantee_overdue,
	current_guarantee_due_this_period,
	unpaid_guarantee,
	total_guarantee_paid,
	guarantee_covered_this_period,
	guarantee_covered_this_month,
	total_guarantee_condoned,
	iof_additional_rate,
	iof_daily_rate,
	iof_installment_limit_rate,
	initial_iof_amount,
	delinquency_iof,
	total_delinquency_iof_paid,
	late_fees,
	total_late_fees_paid,
	total_late_fees_condoned,
	created_at,
    -- MANDATORY FIELDS
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS updated_at
-- DBT SOURCE REFERENCE
from {{ source('raw', 'snc_client_loan_calculations_co') }}
