{{
    config(
        materialized='table',
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

SELECT
    country_code,
    journey_stage_name,
    is_synthetic::BOOLEAN AS is_synthetic,
    journey_stage_homolog,
    -- DATA PLATFORM COLUMNS
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS updated_at
FROM VALUES
    ( 'BR', 'additional-information-br'            , FALSE , 'additional-information-br'           ),
    ( 'BR', 'additional-information-v2-br'         , FALSE , 'additional-information-br'           ),
    ( 'BR', 'background-check-br'                  , FALSE , 'background-check-br'                 ),
    ( 'BR', 'banking-license-partner-br'           , FALSE , 'banking-license-partner-br'          ),
    ( 'BR', 'basic-identity-br'                    , FALSE , 'basic-identity-br'                   ),
    ( 'BR', 'bn-pn-payments-br'                    , FALSE , 'bn-pn-payments-br'                   ),
    ( 'BR', 'cellphone-validation-br'              , FALSE , 'cellphone-validation-br'             ),
    ( 'BR', 'device-information'                   , FALSE , 'device-information-br'               ),
    ( 'BR', 'down-payment-br'                      , FALSE , 'down-payment-br'                     ),
    ( 'BR', 'fraud-check-br'                       , FALSE , 'fraud-check-br'                      ),
    ( 'BR', 'fraud-check-rc-br'                    , FALSE , 'fraud-check-br'                      ),
    ( 'BR', 'identity-photos'                      , FALSE , 'identity-verification-br'            ),
    ( 'BR', 'identity-wa'                          , FALSE , 'identity-verification-br'            ),
    ( 'BR', 'idv-third-party'                      , FALSE , 'idv-third-party-br'                  ),
    ( 'BR', 'loan-acceptance-br'                   , FALSE , 'loan-acceptance-br'                  ),
    ( 'BR', 'loan-proposals-br'                    , FALSE , 'loan-proposals-br'                   ),
    ( 'BR', 'loan-proposals-down-payment-br'       , FALSE , 'loan-proposals-br'                   ),
    ( 'BR', 'personal-information-br'              , FALSE , 'personal-information-br'             ),
    ( 'BR', 'preapproval-summary-br'               , FALSE , 'preapproval-summary-br'              ),
    ( 'BR', 'preconditions-br'                     , FALSE , 'preconditions-br'                    ),
    ( 'BR', 'privacy-policy-br'                    , FALSE , 'privacy-policy-br'                   ),
    ( 'BR', 'privacy-policy-v2-br'                 , FALSE , 'privacy-policy-br'                   ),
    ( 'BR', 'psychometric_assessment'              , FALSE , 'psychometric-assessment-br'          ),
    ( 'BR', 'subproduct-selection-br'              , FALSE , 'subproduct-selection-br'             ),
    ( 'BR', 'underwriting-br'                      , FALSE , 'underwriting-br'                     ),
    ( 'BR', 'underwriting-preapproval-br'          , FALSE , 'underwriting-br'                     ),
    ( 'BR', 'underwriting-rc-br'                   , FALSE , 'underwriting-br'                     ),
    ( 'CO', 'additional-information-santander-co'  , FALSE , 'additional-information-co'           ),
    ( 'CO', 'background-check-co'                  , FALSE , 'background-check-co'                 ),
    ( 'CO', 'basic-identity-co'                    , FALSE , 'basic-identity-co'                   ),
    ( 'CO', 'bnpn-summary-co'                      , FALSE , 'bnpn-summary-co'                     ),
    ( 'CO', 'cellphone-validation-co'              , FALSE , 'cellphone-validation-co'             ),
    ( 'CO', 'device-information'                   , FALSE , 'device-information-co'               ),
    ( 'CO', 'email-verification'                   , FALSE , 'email-verification-co'               ),
    ( 'CO', 'face-verification'                    , FALSE , 'face-verification-co'                ),
    ( 'CO', 'fraud-check-co'                       , FALSE , 'fraud-check-co'                      ),
    ( 'CO', 'fraud-check-rc-co'                    , FALSE , 'fraud-check-co'                      ),
    ( 'CO', 'identity-photos'                      , FALSE , 'identity-verification-co'            ),
    ( 'CO', 'identity-wa'                          , FALSE , 'identity-verification-co'            ),
    ( 'CO', 'loan-acceptance-co'                   , FALSE , 'loan-acceptance-co'                  ),
    ( 'CO', 'loan-acceptance-santander-co'         , FALSE , 'loan-acceptance-co'                  ),
    ( 'CO', 'loan-acceptance-v2-co'                , FALSE , 'loan-acceptance-v2-co'               ),
    ( 'CO', 'loan-proposals-co'                    , FALSE , 'loan-proposals-co'                   ),
    ( 'CO', 'loan-proposals-santander-co'          , FALSE , 'loan-proposals-co'                   ),
    ( 'CO', 'personal-information-co'              , FALSE , 'personal-information-co'             ),
    ( 'CO', 'preapproval-summary-co'               , FALSE , 'preapproval-summary-co'              ),
    ( 'CO', 'preapproval-survey'                   , FALSE , 'preapproval-survey-co'               ),
    ( 'CO', 'preconditions-co'                     , FALSE , 'preconditions-co'                    ),
    ( 'CO', 'preconditions-pago-co'                , FALSE , 'preconditions-co'                    ),
    ( 'CO', 'preconditions-refinance-pago-co'      , FALSE , 'preconditions-refinance-pago-co'     ),
    ( 'CO', 'privacy-policy-co'                    , FALSE , 'privacy-policy-co'                   ),
    ( 'CO', 'privacy-policy-santander-co'          , FALSE , 'privacy-policy-co'                   ),
    ( 'CO', 'privacy-policy-v2-co'                 , FALSE , 'privacy-policy-v2-co'                ),
    ( 'CO', 'pse-payment-co'                       , FALSE , 'pse-payment-co'                      ),
    ( 'CO', 'psychometric_assessment'              , FALSE , 'psychometric-assessment-co'          ),
    ( 'CO', 'refinance-loan-acceptance-co'         , FALSE , 'refinance-loan-acceptance-co'        ),
    ( 'CO', 'refinance-loan-proposal-selection-co' , FALSE , 'refinance-loan-proposal-selection-co'),
    ( 'CO', 'refinance-loan-proposals-co'          , FALSE , 'refinance-loan-proposals-co'         ),
    ( 'CO', 'risk-evaluation-santander-co'         , FALSE , 'risk-evaluation-santander-co'        ),
    ( 'CO', 'underwriting-co'                      , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-pago-co'                 , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-preapproval-co'          , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-preapproval-pago-co'     , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-psychometric-co'         , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-rc-co'                   , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'underwriting-rc-pago-co'              , FALSE , 'underwriting-co'                     ),
    ( 'CO', 'work-information-santander-co'        , FALSE , 'work-information-co'                 )
    AS tab(country_code, journey_stage_name, is_synthetic, journey_stage_homolog)