{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

WITH kordev_toggle_updates AS (
    SELECT
      *
    FROM {{ ref('d_syc_client_migration_segments_co') }}
)
SELECT
  tar.loan_id,
  CAST(tar.origination_date AS DATE) AS origination_date,
  tar.m_vintage,
  tar.amount_originated_this_month,
  tar.moratory_interest_covered_this_month,
  tar.interest_overdue_covered_this_month,
  tar.principal_overdue_covered_this_month,
  tar.guarantee_overdue_covered_this_month,
  tar.current_interest_covered_this_month,
  tar.current_principal_covered_this_month,
  tar.current_guarantee_covered_this_month,
  tar.unpaid_guarantee_covered_this_month,
  tar.unpaid_principal_covered_this_month,
  tar.prepayment_benefit_this_month,
  tar.moratory_interest_condoned_this_month,
  tar.interest_overdue_condoned_this_month,
  tar.principal_overdue_condoned_this_month,
  tar.guarantee_overdue_condoned_this_month,
  tar.current_interest_condoned_this_month,
  tar.current_principal_condoned_this_month,
  tar.current_guarantee_condoned_this_month,
  tar.unpaid_guarantee_condoned_this_month,
  tar.unpaid_principal_condoned_this_month,
  tar.interest_overdue_into_upb_this_month,
  tar.interest_accrued_for_period_in_next_month,
  tar.moratory_interest,
  tar.interest_overdue,
  tar.principal_overdue,
  tar.guarantee_overdue,
  tar.current_interest,
  tar.current_principal,
  tar.current_guarantee,
  tar.unpaid_guarantee,
  tar.unpaid_principal,
  tar.unpaid_interest,
  tar.total_current_interest_condoned,
  tar.total_current_principal_condoned,
  tar.total_interest_overdue_condoned,
  tar.total_principal_overdue_condoned,
  tar.total_unpaid_principal_condoned,
  tar.interest_accrued_this_month,
  tar.moratory_interest_accrued_this_month,
  tar.first_period_interest_condonation_next_month,
  tar.first_period_interest_condonation_this_month,
  tar.client_total_payment,
  tar.client_total_payment_addi,
  tar.client_total_payment_pa,
  tar.late_fees_covered_this_month AS collection_fees_covered_this_month,
  tar.late_fees_condoned_this_month AS collection_fees_condoned_this_month,
  tar.late_fees_accrued_this_month AS collection_fees_accrued_this_month,
  tar.total_late_fees_condoned AS total_collection_fees_condoned,
  tar.late_fees AS unpaid_collection_fees,
  tar.client_id,
  tar.prepayment_benefit_to_principal_this_month,
  tar.prepayment_benefit_to_guarantee_this_month,
  tar.bucket,
  tar.days_past_due,
  tar.created_at,
  tar.total_fga_principal_recovered,
  tar.total_fga_interest_recovered,
  tar.fga_principal_recovered_this_month,
  tar.fga_interest_recovered_this_month,
  tar.total_late_fees_paid AS total_collection_fees_paid,
  tar.late_fees_without_iva_accrued_this_month AS collection_fees_without_iva_accrued_this_month,
  tar.late_fees_iva_accrued_this_month AS collection_fees_iva_accrued_this_month,
  'lms' AS loan_tape_source,
  NOW() AS ingested_at,
  to_timestamp('{{ var("execution_date") }}') AS updated_at
FROM {{ ref('trust_report_trust_accounting_report_co') }} tar
LEFT JOIN kordev_toggle_updates ktu
ON tar.client_id = ktu.client_id
WHERE (ktu.client_id IS NULL) OR (ktu.client_id IS NOT NULL AND tar.m_vintage::DATE < ktu.lms_migrated_at::DATE)
UNION ALL
SELECT
  atr.loan_id,
  CAST(atr.origination_date AS DATE) AS origination_date,
  atr.m_vintage,
  CAST(atr.amount_originated_this_month AS DECIMAL(38,18)) AS amount_originated_this_month,
  CAST(atr.moratory_interest_covered_this_month AS DECIMAL(38,18)) AS moratory_interest_covered_this_month,
  CAST(atr.interest_overdue_covered_this_month AS DECIMAL(38,18)) AS interest_overdue_covered_this_month,
  CAST(atr.principal_overdue_covered_this_month AS DECIMAL(38,18)) AS principal_overdue_covered_this_month,
  CAST(atr.guarantee_overdue_covered_this_month AS DECIMAL(38,18)) AS guarantee_overdue_covered_this_month,
  CAST(atr.current_interest_covered_this_month AS DECIMAL(38,18)) AS current_interest_covered_this_month,
  CAST(atr.current_principal_covered_this_month AS DECIMAL(38,18)) AS current_principal_covered_this_month,
  CAST(atr.current_guarantee_covered_this_month AS DECIMAL(38,18)) AS current_guarantee_covered_this_month,
  CAST(atr.unpaid_guarantee_covered_this_month AS DECIMAL(38,18)) AS unpaid_guarantee_covered_this_month,
  CAST(atr.unpaid_principal_covered_this_month AS DECIMAL(38,18)) AS unpaid_principal_covered_this_month,
  CAST(atr.prepayment_benefit_this_month AS DECIMAL(38,18)) AS prepayment_benefit_this_month,
  CAST(atr.moratory_interest_condoned_this_month AS DECIMAL(38,18)) AS moratory_interest_condoned_this_month,
  CAST(atr.interest_overdue_condoned_this_month AS DECIMAL(38,18)) AS interest_overdue_condoned_this_month,
  CAST(atr.principal_overdue_condoned_this_month AS DECIMAL(38,18)) AS principal_overdue_condoned_this_month,
  CAST(atr.guarantee_overdue_condoned_this_month AS DECIMAL(38,18)) AS guarantee_overdue_condoned_this_month,
  CAST(atr.current_interest_condoned_this_month AS DECIMAL(38,18)) AS current_interest_condoned_this_month,
  CAST(atr.current_principal_condoned_this_month AS DECIMAL(38,18)) AS current_principal_condoned_this_month,
  CAST(atr.current_guarantee_condoned_this_month AS DECIMAL(38,18)) AS current_guarantee_condoned_this_month,
  CAST(atr.unpaid_guarantee_condoned_this_month AS DECIMAL(38,18)) AS unpaid_guarantee_condoned_this_month,
  CAST(atr.unpaid_principal_condoned_this_month AS DECIMAL(38,18)) AS unpaid_principal_condoned_this_month,
  CAST(atr.interest_overdue_into_upb_this_month AS DECIMAL(38,18)) AS interest_overdue_into_upb_this_month,
  0 AS interest_accrued_for_period_in_next_month,
  CAST(atr.moratory_interest AS DECIMAL(38,18)) AS moratory_interest,
  CAST(atr.interest_overdue AS DECIMAL(38,18)) AS interest_overdue,
  CAST(atr.principal_overdue AS DECIMAL(38,18)) AS principal_overdue,
  CAST(atr.guarantee_overdue AS DECIMAL(38,18)) AS guarantee_overdue,
  CAST(atr.current_interest AS DECIMAL(38,18)) AS current_interest,
  0 AS current_principal,
  0 AS current_guarantee,
  CAST(atr.unpaid_guarantee AS DECIMAL(38,18)) AS unpaid_guarantee,
  CAST(atr.unpaid_principal AS DECIMAL(38,18)) AS unpaid_principal,
  CAST(atr.unpaid_interest AS DECIMAL(38,18)) AS unpaid_interest,
  CAST(atr.total_current_interest_condoned AS DECIMAL(38,18)) AS total_current_interest_condoned,
  CAST(atr.total_current_principal_condoned AS DECIMAL(38,18)) AS total_current_principal_condoned,
  CAST(atr.total_interest_overdue_condoned AS DECIMAL(38,18)) AS total_interest_overdue_condoned,
  CAST(atr.total_principal_overdue_condoned AS DECIMAL(38,18)) AS total_principal_overdue_condoned,
  CAST(atr.total_unpaid_principal_condoned AS DECIMAL(38,18)) AS total_unpaid_principal_condoned,
  CAST(atr.interest_accrued_this_month AS DECIMAL(38,18)) AS interest_accrued_this_month,
  CAST(atr.moratory_interest_accrued_this_month AS DECIMAL(38,18)) AS moratory_interest_accrued_this_month,
  0 AS first_period_interest_condonation_next_month,
  0 AS first_period_interest_condonation_this_month,
  CAST(atr.client_total_payment AS DECIMAL(38,18)) AS client_total_payment,
  CAST(atr.client_total_payment_addi AS DECIMAL(38,18)) AS client_total_payment_addi,
  CAST(atr.client_total_payment_pa AS DECIMAL(38,18)) AS client_total_payment_pa,
  CAST(atr.collection_fees_covered_this_month AS DECIMAL(38,18)) AS collection_fees_covered_this_month,
  CAST(atr.collection_fees_condoned_this_month AS DECIMAL(38,18)) AS collection_fees_condoned_this_month,
  CAST(atr.collection_fees_accrued_this_month AS DECIMAL(38,18)) AS collection_fees_accrued_this_month,
  CAST(atr.total_collection_fees_condoned AS DECIMAL(38,18)) AS total_collection_fees_condoned,
  CAST(atr.unpaid_collection_fees AS DECIMAL(38,18)) AS unpaid_collection_fees,
  atr.client_id,
  CAST(atr.prepayment_benefit_to_principal_this_month AS DECIMAL(38,18)) AS prepayment_benefit_to_principal_this_month,
  CAST(atr.prepayment_benefit_to_guarantee_this_month AS DECIMAL(38,18)) AS prepayment_benefit_to_guarantee_this_month,
  atr.bucket,
  atr.days_past_due,
  atr.created_at,
  CAST(atr.total_fga_principal_recovered AS DECIMAL(38,18)) AS total_fga_principal_recovered,
  CAST(atr.total_fga_interest_recovered AS DECIMAL(38,18)) AS total_fga_interest_recovered,
  CAST(atr.fga_principal_recovered_this_month AS DECIMAL(38,18)) AS fga_principal_recovered_this_month,
  CAST(atr.fga_interest_recovered_this_month AS DECIMAL(38,18)) AS fga_interest_recovered_this_month,
  CAST(atr.total_collection_fees_paid AS DECIMAL(19,2)) AS total_collection_fees_paid,
  CAST(atr.collection_fees_without_iva_accrued_this_month AS DECIMAL(19,2)) AS collection_fees_without_iva_accrued_this_month,
  CAST(atr.collection_fees_iva_accrued_this_month AS DECIMAL(19,2)) AS collection_fees_iva_accrued_this_month,
  'kordev' AS loan_tape_source,
  NOW() AS ingested_at,
  to_timestamp('{{ var("execution_date") }}') AS updated_at
FROM {{ source('servicing', 'accounting_trust_report_silver') }} atr
LEFT JOIN kordev_toggle_updates ktu
ON atr.client_id = ktu.client_id
    AND atr.m_vintage::DATE >= ktu.lms_migrated_at::DATE
WHERE ktu.client_id IS NOT NULL