{{
    config(
        materialized='incremental',
        unique_key='conversation_id',
        incremental_strategy='merge',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

--Volume: 58708281 by 2023-09-19
--raw_modeling.kus_conversations
SELECT
    -- MANDATORY FIELDS
    -- MAPPED FIELDS - DIRECT ATTRIBUTES
    conversationId AS conversation_id,
    NULLIF(TRIM(name),'') AS name,
    NULLIF(TRIM(preview),'') AS preview,
    channels AS channels,
    status AS status,
    messageCount AS message_count,
    noteCount AS note_count,
    satisfaction AS satisfaction,
    satisfactionLvl_Channel AS satisfaction_lvl_channel,
    satisfactionLvl_Status AS satisfaction_lvl_status,
    satisfactionLvl_ScheduledFor AS satisfaction_lvl_scheduled_for,
    satisfactionLvl_CreatedAt AS satisfaction_lvl_created_at,
    satisfactionLvl_SentAt AS satisfaction_lvl_sent_at,
    satisfactionLvl_SentBy AS satisfaction_lvl_sent_by,
    satisfactionLvl_Rating AS satisfaction_lvl_rating,
    satisfactionLvl_Score AS satisfaction_lvl_score,
    satisfactionLvl_FirstAnswer AS satisfaction_lvl_first_answer,
    createdAt AS created_at,
    updatedAt AS updated_at,
    modifiedAt AS modified_at,
    lastActivityAt AS last_activity_at,
    lastMessageAt AS last_message_at,
    importedAt AS imported_at,
    spam AS spam,
    ended AS ended,
    endedAt AS ended_at,
    endedReason AS ended_reason,
    endedByType AS ended_by_type,
    tags AS tags,
    suggestedTags AS suggested_tags,
    predictions AS predictions,
    sentiment AS sentiment,
    assignedUsers AS assigned_users,
    assignedTeams AS assigned_teams,
    firstMessageIn_messageId AS first_message_in_message_id,
    firstMessageIn_SentAt AS first_message_in_sent_at,
    firstMessageIn_CreatedAt AS first_message_in_created_at,
    firstMessageIn_DirectionType AS first_message_in_direction_type,
    firstMessageIn_Channel AS first_message_in_channel,
    firstMessageOut_messageId AS first_message_out_message_id,
    firstMessageOut_SentAt AS first_message_out_sent_at,
    firstMessageOut_CreatedAt AS first_message_out_created_at,
    firstMessageOut_DirectionType AS first_message_out_direction_type,
    firstMessageOut_Channel AS first_message_out_channel,
    firstMessageOut_CreatedBy AS first_message_out_created_by,
    lastMessageIn_messageId AS last_message_in_message_id,
    lastMessageIn_SentAt AS last_message_in_sent_at,
    lastMessageIn_CreatedAt AS last_message_in_created_at,
    lastMessageOut_messageId AS last_message_out_message_id,
    lastMessageOut_SentAt AS last_message_out_sent_at,
    lastMessageOut_CreatedAt AS last_message_out_created_at,
    firstResponse_Id AS first_response_id,
    firstResponse_BusinessTime AS first_response_business_time,
    firstResponse_CreatedAt AS first_response_created_at,
    firstResponse_CreatedBy AS first_response_created_by,
    firstResponse_SentAt AS first_response_sent_at,
    firstResponse_ResponseTime AS first_response_response_time,
    lastResponse_Id AS last_response_id,
    lastResponse_BusinessTime AS last_response_business_time,
    lastResponse_CreatedAt AS last_response_created_at,
    lastResponse_CreatedBy AS last_response_created_by,
    firstDone_CreatedByTeams AS first_done_created_by_teams,
    firstDone_AssignedTeams AS first_done_assigned_teams,
    firstDone_AssignedUsers AS first_done_assigned_users,
    firstDone_BusinessTime AS first_done_business_time,
    firstDone_CreatedAt AS first_done_created_at,
    firstDone_CreatedBy AS first_done_created_by,
    firstDone_lastMessageDirection AS first_done_last_message_direction,
    firstDone_lastMessageDirectionType AS first_done_last_message_direction_type,
    lastDone_CreatedByTeams AS last_done_created_by_teams,
    lastDone_AssignedTeams AS last_done_assigned_teams,
    lastDone_AssignedUsers AS last_done_assigned_users,
    lastDone_BusinessTime AS last_done_business_time,
    lastDone_CreatedAt AS last_done_created_at,
    lastDone_CreatedBy AS last_done_created_by,
    lastDone_lastMessageDirection AS last_done_last_message_direction,
    lastDone_lastMessageDirectionType AS last_done_last_message_direction_type,
    doneCount AS done_count,
    snoozeCount AS snooze_count,
    reopenCount AS reopen_count,
    direction AS direction,
    lastMessageDirection AS last_message_direction,
    outboundMessageCount AS outbound_message_count,
    inboundMessageCount AS inbound_message_count,
    rev AS rev,
    priority AS priority,
    externalQueue AS external_queue,
    totalSnooze_BusinessTime AS total_snooze_business_time,
    totalDone_BusinessTime AS total_done_business_time,
    totalOpen_BusinessTime AS total_open_business_time,
    totalOpen_BusinessTimeSinceLastDone AS total_open_business_time_since_last_done,
    mergedTarget AS merged_target,
    sla_name AS sla_name,
    sla_version AS sla_version,
    sla_matchedAt AS sla_matched_at,
    sla_breached AS sla_breached,
    sla_status AS sla_status,
    sla_firstBreachAt AS sla_first_breach_at,
    sla_satisfiedAt AS sla_satisfied_at,
    orgId AS org_id,
    customerId AS customer_id,
    endedById AS ended_by_id,
    queueId AS queue_id,
    slaId AS sla_id,
    referenceDate AS reference_date,
    year AS reference_date_year,
    month AS reference_date_month,
    to_timestamp(modificationHistory_nameAt) AS modification_history_name_at,
    to_timestamp(modificationHistory_priorityAt) AS modification_history_priority_at,
    to_timestamp(modificationHistory_channelAt) AS modification_history_channel_at,
    to_timestamp(modificationHistory_assignedTeamsAt) AS modification_history_assigned_teams_at,
    to_timestamp(modificationHistory_assignedUsersAt) AS modification_history_assigned_users_at,
    to_timestamp(modificationHistory_brandAt) AS modification_history_brand_at,
    to_timestamp(modificationHistory_defaultLangAt) AS modification_history_default_lang_at,
    to_timestamp(modificationHistory_statusAt) AS modification_history_status_at,
    to_timestamp(modificationHistory_tagsAt) AS modification_history_tags_at,
    to_timestamp(modificationHistory_customAt) AS modification_history_custom_at,
    -- CUSTOM ATTRIBUTES
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS data_platform_updated_at
-- DBT SOURCE REFERENCE
FROM {{ source('raw_modeling', 'kus_conversations') }}
-- DBT INCREMENTAL SENTENCE

{% if is_incremental() %}
    WHERE to_date(updatedAt) BETWEEN (to_date("{{ var('start_date') }}"- INTERVAL "{{var('incremental_slack_time_in_days')}}" DAY)) AND to_date("{{ var('end_date') }}")
    AND CAST(updatedAt AS TIMESTAMP) BETWEEN (to_timestamp("{{ var('start_date') }}"- INTERVAL "{{var('incremental_slack_time_in_days')}}" DAY)) AND to_timestamp("{{ var('end_date')}}")
{% endif %}
