{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}
SELECT
  o.opportunity_id,
  o.opportunity_name,
  o.opportunity_slug,
  o.opportunity_amount,
  o.opportunity_is_closed,
  o.opportunity_is_deleted,
  o.opportunity_is_won,
  o.opportunity_stage_name,
  s.opportunity_stage_default_probability,
  s.opportunity_stage_sort_order,
  o.opportunity_ally_cluster,
  o.opportunity_close_date,
  o.opportunity_created_date,
  o.opportunity_termination_date,
  o.opportunity_account_vertical,
  o.opportunity_record_type_id,
  rt.record_type_name AS opportunity_record_type_name,
  a.account_id,
  a.account_name,
  a.account_kam_user_id,
  u.user_name AS account_kam_name,
  u.user_email AS account_kam_email,
  us.user_name AS account_hunter_name,
  a.account_pod,
  o.opportunity_link,
  o.opportunity_lastmoddate,
  o.opportunity_systemmodstamp,
  -- Product fields
  o.opportunity_activation_owner,
  o.opportunity_company_verification_report_url,
  o.opportunity_is_ofac,
  o.opportunity_kyp_go,
  o.opportunity_kyp_reviewer_id,
  o.opportunity_company_verification,
  o.opportunity_legal_representative_verification,
  o.opportunity_loss_reason,
  o.opportunity_reason_on_hold,
  o.opportunity_not_sql_reason,
  o.opportunity_kyp_reject_reason,
  o.opportunity_check_in_date_kyp,
  o.opportunity_check_out_date_kyp,
  o.opportunity_opportunity_check_in_activation_date,
  o.opportunity_opportunity_check_in_onboarding_date,
  o.opportunity_opportunity_training_date,
  o.opportunity_field_sales_business,
  o.opportunity_descartado_details,
  o.opportunity_consolidation_date,
  o.opportunity_aml,
  o.opportunity_aml_reason,
  o.opportunity_accept_credit_card,
  o.opportunity_accept_sistecredito,
  o.opportunity_kyp_approval_details,
  o.opportunity_kyp_approval_reason,
  o.opportunity_kyp_comments,
  o.opportunity_kyp_decision,
  o.opportunity_kyp_details,
  o.opportunity_not_accepted_product_type,
  o.opportunity_rejection_details_2,
  o.opportunity_rejection_details,
  o.opportunity_replicas,
  o.opportunity_risky_neighborhood,
  o.opportunity_risky_vertical,
  o.opportunity_ally_store_geolocation,
  o.opportunity_ally_store_latitude,
  o.opportunity_ally_store_longitude,
  o.opportunity_first_origination_date,
  o.opportunity_type,
  o.opportunity_average_order_value,
  -- Fraud fields
  o.opportunity_created_by_id,
  o.opportunity_bank_code,
  o.opportunity_bank_name,
  o.opportunity_bank_account_type,
  o.opportunity_bank_account_number,
  o.opportunity_certificado_bancario,
  o.opportunity_application_status,
  o.opportunity_mql_reason,
  o.opportunity_potential_gmv,
  o.opportunity_business_address_latitude,
  o.opportunity_business_address_longitude,
  o.opportunity_business_address_city,
  o.opportunity_business_address_street,
  o.opportunity_razon_social,
  o.opportunity_business_address_state_code,
  o.opportunity_business_address_postal_code,
  o.opportunity_business_address_country_code,
  o.opportunity_business_address_geo_code,
  o.opportunity_business_address,
  o.opportunity_sector_comercio,
  o.opportunity_vertical_formula,
  o.opportunity_number_of_stores,
  o.opportunity_vertical,
  o.opportunity_razon_social_pago,
  o.opportunity_on_hold,
  o.opportunity_legal_representative,
  o.opportunity_fotocopia_cedula_representante,
  o.opportunity_promotion_end,
  o.opportunity_date_success_graduation,
  o.opportunity_last_referenced_date,
  o.opportunity_last_stage_change_date,
  o.opportunity_push_count,
  o.opportunity_fiscal_year,
  o.opportunity_fiscal_quarter,
  o.opportunity_owner_id,
  o.opportunity_next_step,
  o.opportunity_state,
  o.opportunity_cities,
  o.opportunity_contact_id,
  o.opportunity_campaign_id,
  o.opportunity_termination_reason,
  o.opportunity_tipo_contribuyente,
  o.opportunity_camara_comercio_url,
  o.opportunity_last_amount_changed,
  o.opportunity_address_complement,
  o.opportunity_contact_mobile,
  o.opportunity_last_close_date,
  o.opportunity_technical_contact,
  o.opportunity_main_onboarding,
  o.opportunity_sub_stage,
  o.opportunity_tiers,
  o.opportunity_channel,
  o.opportunity_ecommerce_cms,
  o.opportunity_company_legal_email,
  o.opportunity_rango_promedio_compra,
  o.opportunity_smbs_monthly_sales,
  o.opportunity_ally_total_monthly_sales,
  o.opportunity_ciuu,
  o.opportunity_nit,
  o.opportunity_dv,
  o.opportunity_address_line_1,
  o.opportunity_address_line_2,
  o.opportunity_t_c,
  o.opportunity_paylink_type,
  o.opportunity_utm_medium,
  o.opportunity_utm_source,
  o.opportunity_utm_campaign,
  o.opportunity_utm_term,
  o.opportunity_utm_content,
  o.application_form_id,
  -- MANDATORY FIELDS
  NOW() AS ingested_at,
  to_timestamp('{{ var("execution_date") }}') AS updated_at,
  o.airbyte_emitted_at AS opportunity_airbyte_emitted_at,
  o.ingested_from_s3_at AS opportunity_ingested_from_s3_at
FROM      {{ ref('salesforce_opportunity')}} AS o
LEFT JOIN {{ ref('salesforce_account')}} AS a ON o.account_id = a.account_id
LEFT JOIN {{ ref('salesforce_user')}} AS us ON a.account_hunter_user_id = us.user_id
LEFT JOIN {{ ref('salesforce_user')}} AS u ON a.account_kam_user_id = u.user_id
LEFT JOIN {{ ref('salesforce_opportunity_stage')}} AS s ON o.opportunity_stage_name = s.opportunity_stage_api_name
LEFT JOIN {{ ref('salesforce_record_type')}} AS rt ON o.opportunity_record_type_id = rt.record_type_id