{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

--raw.salesforce_applicationform_full_refresh_overwrite
SELECT
	Id AS application_form_id,
	Account__c AS application_form_account,
	Power_of_1__c AS application_form_power_of_1,
	CurrentStep__c AS application_form_current_step,
	IsDeleted AS application_form_is_deleted,
	Status__c AS application_form_status,
	StepsCompleted__c AS application_form_steps_completed,
	SubmittedForm__c AS application_form_submitted_form,
	Channels__c AS application_form_channels,
	Contact__c AS application_form_contact,
	EsContactoMercadeo__c AS application_form_es_contacto_mercadeo,
	EsContactoPrincipal__c AS application_form_es_contacto_principal,
	EsRepresentanteLegal__c AS application_form_es_representante_legal,
	Name AS application_form_name,
	PoseePorcentajeEmpresa__c AS application_form_posee_porcentaje_empresa,
	GuestUserEmail__c AS application_form_guest_user_email,
	RepresentanteLegal__c AS application_form_representante_legal,
	StartStep0__c.member0 AS application_form_start_step_0,
	StartStep1__c.member0 AS application_form_start_step_1,
	StartStep2__c.member0 AS application_form_start_step_2,
	StartStep3__c.member0 AS application_form_start_step_3,
	StartStep4__c.member0 AS application_form_start_step_4,
	StartStep5__c.member0 AS application_form_start_step_5,
	StartStep6__c.member0 AS application_form_start_step_6,
	StartStep7__c.member0 AS application_form_start_step_7,
	StartStep8__c.member0 AS application_form_start_step_8,
	StartStep9__c.member0 AS application_form_start_step_9,
	StartStep10__c.member0 AS application_form_start_step_10,
	StartStep11__c.member0 AS application_form_start_step_11,
	StartStep12__c.member0 AS application_form_start_step_12,
	EndStep0__c.member0 AS application_form_end_step_0,
	EndStep1__c.member0 AS application_form_end_step_1,
	EndStep2__c.member0 AS application_form_end_step_2,
	EndStep3__c.member0 AS application_form_end_step_3,
	EndStep4__c.member0 AS application_form_end_step_4,
	EndStep5__c.member0 AS application_form_end_step_5,
	EndStep6__c.member0 AS application_form_end_step_6,
	EndStep7__c.member0 AS application_form_end_step_7,
	EndStep8__c.member0 AS application_form_end_step_8,
	EndStep9__c.member0 AS application_form_end_step_9,
	EndStep10__c.member0 AS application_form_end_step_10,
	EndStep11__c.member0 AS application_form_end_step_11,
	EndStep12__c.member0 AS application_form_end_step_12,
	Step0Completed__c AS application_form_step_0_completed,
	Step1Completed__c AS application_form_step_1_completed,
	Step2Completed__c AS application_form_step_2_completed,
	Step3Completed__c AS application_form_step_3_completed,
	Step4Completed__c AS application_form_step_4_completed,
	Step5Completed__c AS application_form_step_5_completed,
	Step6Completed__c AS application_form_step_6_completed,
	Step7Completed__c AS application_form_step_7_completed,
	Step8Completed__c AS application_form_step_8_completed,
	Step9Completed__c AS application_form_step_9_completed,
	Step10Completed__c AS application_form_step_10_completed,
	Step11Completed__c AS application_form_step_11_completed,
	Step12Completed__c AS application_form_step_12_completed,
	StepTime0__c AS application_form_step_time_0,
	StepTime1__c AS application_form_step_time_1,
	StepTime2__c AS application_form_step_time_2,
	StepTime3__c AS application_form_step_time_3,
	StepTime4__c AS application_form_step_time_4,
	StepTime5__c AS application_form_step_time_5,
	StepTime6__c AS application_form_step_time_6,
	StepTime7__c AS application_form_step_time_7,
	StepTime8__c AS application_form_step_time_8,
	StepTime9__c AS application_form_step_time_9,
	StepTime10__c AS application_form_step_time_10,
	StepTime11__c AS application_form_step_time_11,
	StepTime12__c AS application_form_step_time_12,
	CreatedDate.member0 AS application_form_created_date,
	StartForm__c AS application_form_start_form,
	EndForm__c AS application_form_end_form,
	LastActivityDate.member0 AS application_form_last_activity_date,
	LastModifiedDate.member0 AS application_form_last_modified_date,
	FormTime__c AS application_form_form_time,
	TotalTimeDays__c AS application_form_total_time_days,
	TotalTimeHours__c AS application_form_total_time_hours,
	TotalTimeMinutes__c AS application_form_total_time_minutes,
	TotalTimeSeconds__c AS application_form_total_time_seconds,
	LastModifiedById AS application_form_last_modified_by,
	CreatedById AS application_form_created_by,
	OwnerId AS application_form_owner_id,
	-- MANDATORY FIELDS
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS updated_at,
    `_airbyte_emitted_at` AS airbyte_emitted_at,
    ingested_from_s3_at
    -- CUSTOM ATTRIBUTES
    -- Fill with your custom attributes
-- DBT SOURCE REFERENCE
from {{ source('raw', 'salesforce_applicationform_full_refresh_overwrite') }}



