{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

--raw.salesforce_opportunity_full_refresh_overwrite
SELECT
	Id AS opportunity_id,
	AccountId AS account_id,
	Name AS opportunity_name,
	NULLIF(Slug_Discussed_with_the_Ally__c,'(No value)') AS opportunity_slug,
	Amount AS opportunity_amount,
	IsClosed AS opportunity_is_closed,
	IsDeleted AS opportunity_is_deleted,
	IsWon 	AS opportunity_is_won,
	StageName AS opportunity_stage_name,
	Ally_Cluster__c AS opportunity_ally_cluster,
	CloseDate.member0 AS opportunity_close_date,
	CreatedDate.member0 AS opportunity_created_date,
	Termination_Date__c.member0 AS opportunity_termination_date,
	COALESCE(Vertical_formula__c,Vertical__c) AS opportunity_account_vertical,
	City__c AS opportunity_city,
	Department__c AS opportunity_department,
	RecordTypeId AS opportunity_record_type_id,
	CONCAT('https://addi.lightning.force.com/lightning/r/Opportunity/',Id ,'/view') AS opportunity_link,
	LastModifiedDate.member0 AS opportunity_lastmoddate,
	SystemModstamp.member0 AS opportunity_systemmodstamp,
	-- Product fields
	Activation_Owner__c AS opportunity_activation_owner,
	Company_Verification_Report_URL__c AS opportunity_company_verification_report_url,
	OFAC__c AS opportunity_is_ofac,
	KYP_go__c AS opportunity_kyp_go,
	KYP_Reviewer__c AS opportunity_kyp_reviewer_id,
	Company_Verification__c AS opportunity_company_verification,
	Legal_Representative_Verification__c AS opportunity_legal_representative_verification,
	Loss_Reason__c AS opportunity_loss_reason,
	Reason_of_On_Hold__c AS opportunity_reason_on_hold,
	Not_SQL_Reason__c AS opportunity_not_sql_reason,
	KYP_Reject_Reason__c AS opportunity_kyp_reject_reason,
	Check_in_Date_KYP__c.member0 AS opportunity_check_in_date_kyp,
	Checkout_Date_KYP__c.member0 AS opportunity_check_out_date_kyp,
	Checkin_Date_Activation__c.member0 AS opportunity_opportunity_check_in_activation_date,
	Check_in_Date_Onboarding__c.member0 AS opportunity_opportunity_check_in_onboarding_date,
	Training_Date__c.member0 AS opportunity_opportunity_training_date,
    Field_Sales_Business__c AS opportunity_field_sales_business,
    Descartado_Details__c AS opportunity_descartado_details,
    Date_of_Consolidation__c.member0 AS opportunity_consolidation_date,
    AML__c AS opportunity_aml,
    AML_Reason__c AS opportunity_aml_reason,
    Accept_Credit_Card__c AS opportunity_accept_credit_card,
    Accept_Sistecredito__c AS opportunity_accept_sistecredito,
    KYP_Approval_Details__c AS opportunity_kyp_approval_details,
    KYP_Approval_Reason__c AS opportunity_kyp_approval_reason,
    KYP_Comments__c AS opportunity_kyp_comments,
    KYP_Decision__c AS opportunity_kyp_decision,
    KYP_Details__c AS opportunity_kyp_details,
    Not_accepted_product_type__c AS opportunity_not_accepted_product_type,
    Rejection_Details2__c AS opportunity_rejection_details_2,
    Rejection_Details__c AS opportunity_rejection_details,
    Replicas__c AS opportunity_replicas,
    Risky_Neighborhood__c AS opportunity_risky_neighborhood,
    Risky_Vertical__c AS opportunity_risky_vertical,
    Ally_Store_Geolocation__c AS opportunity_ally_store_geolocation,
    Ally_Store_Geolocation__Latitude__s AS opportunity_ally_store_latitude,
    Ally_Store_Geolocation__Longitude__s AS opportunity_ally_store_longitude,
    Date_of_first_origination__c.member0 AS opportunity_first_origination_date,
    Type AS opportunity_type,
    Average_Ticket__c AS opportunity_average_order_value,
	-- Fraud fields
	CreatedById AS opportunity_created_by_id,
    Bank_Code__c AS opportunity_bank_code,
    Bank_Name__c AS opportunity_bank_name,
    Bank_Account_Type__c AS opportunity_bank_account_type,
    Bank_Account_Number__c AS opportunity_bank_account_number,
    Certificado_bancario_URL__c AS opportunity_certificado_bancario,
    Application_Status__c AS opportunity_application_status,
    Reason_of_MQL_Not_Approved__c AS opportunity_mql_reason,
    Addi_Potential_GMV__c AS opportunity_potential_gmv,
    Business_Address__Latitude__s AS opportunity_business_address_latitude,
    Business_Address__Longitude__s AS opportunity_business_address_longitude,
    Business_Address__City__s AS opportunity_business_address_city,
    Business_Address__Street__s AS opportunity_business_address_street,
    Razao_Social_Razon_Social__c AS opportunity_razon_social,
    Business_Address__StateCode__s AS opportunity_business_address_state_code,
    Business_Address__PostalCode__s AS opportunity_business_address_postal_code,
    Business_Address__CountryCode__s AS opportunity_business_address_country_code,
    Business_Address__GeocodeAccuracy__s AS opportunity_business_address_geo_code,
    Business_Address__c AS opportunity_business_address,
    Sector_del_Comercio_Aliados__c AS opportunity_sector_comercio,
    Vertical_formula__c AS opportunity_vertical_formula,
    Number_of_Stores__c AS opportunity_number_of_stores,
    Vertical__c AS opportunity_vertical,
    Razon_Social_Pago__c AS opportunity_razon_social_pago,
    On_Hold__c AS opportunity_on_hold,
    Legal_Representative__c AS opportunity_legal_representative,
    Fotocopia_de_la_c_dula_del_representante__c AS opportunity_fotocopia_cedula_representante,
    Promotion_end__c AS opportunity_promotion_end,
    Date_Success_Graduation__c AS opportunity_date_success_graduation,
    LastReferencedDate.member0 AS opportunity_last_referenced_date,
    LastStageChangeDate.member0 AS opportunity_last_stage_change_date,
    PushCount AS opportunity_push_count,
    FiscalYear AS opportunity_fiscal_year,
    FiscalQuarter AS opportunity_fiscal_quarter,
    OwnerId AS opportunity_owner_id,
    NextStep AS opportunity_next_step,
    State__c AS opportunity_state,
    Cities__c AS opportunity_cities,
    ContactId AS opportunity_contact_id,
    CampaignId AS opportunity_campaign_id,
    Termination_Reason__c AS opportunity_termination_reason,
    Tipo_de_contribuyente__c AS opportunity_tipo_contribuyente,
    Camara_de_Comercio_URL__c AS opportunity_camara_comercio_url,
    LastAmountChangedHistoryId AS opportunity_last_amount_changed,
    p_o_p_Address_complement__c AS opportunity_address_complement,
    Associated_Contact_Mobile__c AS opportunity_contact_mobile,
    LastCloseDateChangedHistoryId AS opportunity_last_close_date,
    Technical_contact_Name_Phone_Email__c AS opportunity_technical_contact,
    Main_Onboarding__c AS opportunity_main_onboarding,
    Sub_Stage__c AS opportunity_sub_stage,
    Tiers__c AS opportunity_tiers,
    Channel__c as opportunity_channel,
    Paylink_Type__c as opportunity_paylink_type,
    Ecommerce_CMS__c as opportunity_ecommerce_cms,
    utm_medium__c AS opportunity_utm_medium,
    utm_source__c AS opportunity_utm_source,
    utm_campaign__c AS opportunity_utm_campaign,
    utm_term__c AS opportunity_utm_term,
    utm_content__c AS opportunity_utm_content,
    Company_Legal_Email__c AS opportunity_company_legal_email,
    RangoPromedioCompra__c AS opportunity_rango_promedio_compra,
    SMBs_monthly_sales__c AS opportunity_smbs_monthly_sales,
    Ally_Total_Monthly_Sales__c AS opportunity_ally_total_monthly_sales,
    CIUU__c AS opportunity_ciuu,
    NIT__c AS opportunity_nit,
    DV__c AS opportunity_dv,
    Address_Line_1__c AS opportunity_address_line_1,
    Address_Line_2__c AS opportunity_address_line_2,
    T_C__c AS opportunity_t_c,
    ApplicationForm__c AS application_form_id,
	-- MANDATORY FIELDS
    NOW() AS ingested_at,
    to_timestamp('{{ var("execution_date") }}') AS updated_at,
    `_airbyte_emitted_at` AS airbyte_emitted_at,
    ingested_from_s3_at
    -- CUSTOM ATTRIBUTES
    -- Fill with your custom attributes
-- DBT SOURCE REFERENCE
from {{ source('raw', 'salesforce_opportunity_full_refresh_overwrite') }}



