{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

SELECT
  CAST(loan_id AS string) AS loan_id,
  CAST(client_id AS string) AS client_id,
  CAST(amount_originated_this_month AS decimal(38,18)) AS amount_originated_this_month,
  CAST(bucket AS string) AS bucket,
  CAST(cancellation_reason AS string) AS cancellation_reason,
  CAST(cancelled_and_annulled_loan_initial_balance AS decimal(38,18)) AS cancelled_and_annulled_loan_initial_balance,
  CAST(current_interest_covered_this_month AS decimal(38,18)) AS current_interest_covered_this_month,
  CAST(current_principal_condoned_this_month AS decimal(38,18)) AS current_principal_condoned_this_month,
  CAST(current_principal_covered_this_month AS decimal(38,18)) AS current_principal_covered_this_month,
  CAST(days_past_due AS int) AS days_past_due,
  CAST(first_period_interest_condonation_next_month AS decimal(38,18)) AS first_period_interest_condonation_next_month,
  CAST(first_period_interest_condonation_this_month AS decimal(38,18)) AS first_period_interest_condonation_this_month,
  CAST(full_payment_guarantee_condonation_adjustment AS decimal(38,18)) AS full_payment_guarantee_condonation_adjustment,
  CAST(created_at AS timestamp) AS created_at,
  CAST(initial_loan_balance AS decimal(38,18)) AS initial_loan_balance,
  CAST(interest_accrued_for_period_in_next_month AS decimal(38,18)) AS interest_accrued_for_period_in_next_month,
  CAST(interest_accrued_this_month AS decimal(38,18)) AS interest_accrued_this_month,
  CAST(interest_overdue_covered_this_month AS decimal(38,18)) AS interest_overdue_covered_this_month,
  CAST(interest_overdue_into_upb_this_month AS decimal(38,18)) AS interest_overdue_into_upb_this_month,
  CAST(loan_ownership AS string) AS loan_ownership,
  CAST(moratory_interest_accrued_this_month AS decimal(38,18)) AS moratory_interest_accrued_this_month,
  CAST(moratory_interest_condoned_this_month AS decimal(38,18)) AS moratory_interest_condoned_this_month,
  CAST(moratory_interest_covered_this_month AS decimal(38,18)) AS moratory_interest_covered_this_month,
  CAST(origination_date AS date) AS origination_date,
  CAST(payment_redistribution_principal_adjustment AS decimal(38,18)) AS payment_redistribution_principal_adjustment,
  CAST(prepayment_benefit_this_month AS decimal(38,18)) AS prepayment_benefit_this_month,
  CAST(prepayment_benefit_to_principal_this_month AS decimal(38,18)) AS prepayment_benefit_to_principal_this_month,
  CAST(principal_conciliation AS decimal(38,18)) AS principal_conciliation,
  CAST(principal_conciliation_ok AS boolean) AS principal_conciliation_ok,
  CAST(principal_from_annulled_payments AS decimal(38,18)) AS principal_from_annulled_payments,
  CAST(principal_from_new_registered_payments AS decimal(38,18)) AS principal_from_new_registered_payments,
  CAST(principal_overdue_condoned_this_month AS decimal(38,18)) AS principal_overdue_condoned_this_month,
  CAST(principal_overdue_covered_this_month AS decimal(38,18)) AS principal_overdue_covered_this_month,
  CAST(report_date AS date) AS report_date,
  CAST(sale_date AS date) AS sale_date,
  CAST(sold_amount AS decimal(38,18)) AS sold_amount,
  CAST(total_current_interest_condoned AS decimal(38,18)) AS total_current_interest_condoned,
  CAST(total_guarantee_covered AS decimal(38,18)) AS total_guarantee_covered,
  CAST(total_interest_overdue_condoned AS decimal(38,18)) AS total_interest_overdue_condoned,
  CAST(total_principal_condoned AS decimal(38,18)) AS total_principal_condoned,
  CAST(total_principal_covered AS decimal(38,18)) AS total_principal_covered,
  CAST(unpaid_principal AS decimal(38,18)) AS unpaid_principal,
  CAST(unpaid_principal_condoned_this_month AS decimal(38,18)) AS unpaid_principal_condoned_this_month,
  CAST(unpaid_principal_covered_this_month AS decimal(38,18)) AS unpaid_principal_covered_this_month,
  CAST(usury_rate_adjustment_impact_on_principal AS decimal(38,18)) AS usury_rate_adjustment_impact_on_principal,
  CAST(usury_rate_correction AS decimal(38,18)) AS usury_rate_correction,
  CAST(value_to_transfer_to_trust AS decimal(38,18)) AS value_to_transfer_to_trust,
  CAST(interest_overdue_condoned_this_month AS decimal(38,18)) AS interest_overdue_condoned_this_month,
  CAST(current_interest_condoned_this_month AS decimal(38,18)) AS current_interest_condoned_this_month,
  CAST(total_fga_principal_recovered AS decimal(38,18)) AS total_fga_principal_recovered,
  CAST(total_fga_interest_recovered AS decimal(38,18)) AS total_fga_interest_recovered,
  CAST(fga_principal_recovered_this_month AS decimal(38,18)) AS fga_principal_recovered_this_month,
  CAST(fga_interest_recovered_this_month AS decimal(38,18)) AS fga_interest_recovered_this_month,
NOW() AS ingested_at,
to_timestamp('{{ var("execution_date") }}') AS updated_at
FROM {{ source('raw', 'trust_report_trust_report_co')}}