{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

SELECT
  CAST(loan_id AS string) AS loan_id,
  CAST(origination_date AS date) AS origination_date,
  CAST(date AS date) AS m_vintage,
  CAST(amount_originated_this_month AS decimal(38,18)) AS amount_originated_this_month,
  CAST(moratory_interest_covered_this_month AS decimal(38,18)) AS moratory_interest_covered_this_month,
  CAST(interest_overdue_covered_this_month AS decimal(38,18)) AS interest_overdue_covered_this_month,
  CAST(principal_overdue_covered_this_month AS decimal(38,18)) AS principal_overdue_covered_this_month,
  CAST(guarantee_overdue_covered_this_month AS decimal(38,18)) AS guarantee_overdue_covered_this_month,
  CAST(current_interest_covered_this_month AS decimal(38,18)) AS current_interest_covered_this_month,
  CAST(current_principal_covered_this_month AS decimal(38,18)) AS current_principal_covered_this_month,
  CAST(current_guarantee_covered_this_month AS decimal(38,18)) AS current_guarantee_covered_this_month,
  CAST(unpaid_guarantee_covered_this_month AS decimal(38,18)) AS unpaid_guarantee_covered_this_month,
  CAST(unpaid_principal_covered_this_month AS decimal(38,18)) AS unpaid_principal_covered_this_month,
  CAST(prepayment_benefit_this_month AS decimal(38,18)) AS prepayment_benefit_this_month,
  CAST(moratory_interest_condoned_this_month AS decimal(38,18)) AS moratory_interest_condoned_this_month,
  CAST(interest_overdue_condoned_this_month AS decimal(38,18)) AS interest_overdue_condoned_this_month,
  CAST(principal_overdue_condoned_this_month AS decimal(38,18)) AS principal_overdue_condoned_this_month,
  CAST(guarantee_overdue_condoned_this_month AS decimal(38,18)) AS guarantee_overdue_condoned_this_month,
  CAST(current_interest_condoned_this_month AS decimal(38,18)) AS current_interest_condoned_this_month,
  CAST(current_principal_condoned_this_month AS decimal(38,18)) AS current_principal_condoned_this_month,
  CAST(current_guarantee_condoned_this_month AS decimal(38,18)) AS current_guarantee_condoned_this_month,
  CAST(unpaid_guarantee_condoned_this_month AS decimal(38,18)) AS unpaid_guarantee_condoned_this_month,
  CAST(unpaid_principal_condoned_this_month AS decimal(38,18)) AS unpaid_principal_condoned_this_month,
  CAST(interest_overdue_into_upb_this_month AS decimal(38,18)) AS interest_overdue_into_upb_this_month,
  CAST(interest_accrued_for_period_in_next_month AS decimal(38,18)) AS interest_accrued_for_period_in_next_month,
  CAST(moratory_interest AS decimal(38,18)) AS moratory_interest,
  CAST(interest_overdue AS decimal(38,18)) AS interest_overdue,
  CAST(principal_overdue AS decimal(38,18)) AS principal_overdue,
  CAST(guarantee_overdue AS decimal(38,18)) AS guarantee_overdue,
  CAST(current_interest AS decimal(38,18)) AS current_interest,
  CAST(current_principal AS decimal(38,18)) AS current_principal,
  CAST(current_guarantee AS decimal(38,18)) AS current_guarantee,
  CAST(unpaid_guarantee AS decimal(38,18)) AS unpaid_guarantee,
  CAST(unpaid_principal AS decimal(38,18)) AS unpaid_principal,
  CAST(unpaid_interest AS decimal(38,18)) AS unpaid_interest,
  CAST(total_current_interest_condoned AS decimal(38,18)) AS total_current_interest_condoned,
  CAST(total_current_principal_condoned AS decimal(38,18)) AS total_current_principal_condoned,
  CAST(total_interest_overdue_condoned AS decimal(38,18)) AS total_interest_overdue_condoned,
  CAST(total_principal_overdue_condoned AS decimal(38,18)) AS total_principal_overdue_condoned,
  CAST(total_unpaid_principal_condoned AS decimal(38,18)) AS total_unpaid_principal_condoned,
  CAST(interest_accrued_this_month AS decimal(38,18)) AS interest_accrued_this_month,
  CAST(moratory_interest_accrued_this_month AS decimal(38,18)) AS moratory_interest_accrued_this_month,
  CAST(first_period_interest_condonation_next_month AS decimal(38,18)) AS first_period_interest_condonation_next_month,
  CAST(first_period_interest_condonation_this_month AS decimal(38,18)) AS first_period_interest_condonation_this_month,
  CAST(client_total_payment AS decimal(38,18)) AS client_total_payment,
  CAST(client_total_payment_addi AS decimal(38,18)) AS client_total_payment_addi,
  CAST(client_total_payment_pa AS decimal(38,18)) AS client_total_payment_pa,
  CAST(late_fees_covered_this_month AS decimal(38,18)) AS late_fees_covered_this_month,
  CAST(late_fees_condoned_this_month AS decimal(38,18)) AS late_fees_condoned_this_month,
  CAST(late_fees_accrued_this_month AS decimal(38,18)) AS late_fees_accrued_this_month,
  CAST(total_late_fees_condoned AS decimal(38,18)) AS total_late_fees_condoned,
  CAST(late_fees AS decimal(38,18)) AS late_fees,
  CAST(client_id AS string) AS client_id,
  CAST(prepayment_benefit_to_principal_this_month AS decimal(38,18)) AS prepayment_benefit_to_principal_this_month,
  CAST(prepayment_benefit_to_guarantee_this_month AS decimal(38,18)) AS prepayment_benefit_to_guarantee_this_month,
  CAST(bucket AS string) AS bucket,
  CAST(days_past_due AS int) AS days_past_due,
  CAST(created_at AS timestamp) AS created_at,
  CAST(total_fga_principal_recovered AS decimal(38,18)) AS total_fga_principal_recovered,
  CAST(total_fga_interest_recovered AS decimal(38,18)) AS total_fga_interest_recovered,
  CAST(fga_principal_recovered_this_month AS decimal(38,18)) AS fga_principal_recovered_this_month,
  CAST(fga_interest_recovered_this_month AS decimal(38,18)) AS fga_interest_recovered_this_month,
  CAST(total_late_fees_paid AS decimal(19,2)) AS total_late_fees_paid,
  CAST(late_fees_without_iva_accrued_this_month AS decimal(19,2)) AS late_fees_without_iva_accrued_this_month,
  CAST(late_fees_iva_accrued_this_month AS decimal(19,2)) AS late_fees_iva_accrued_this_month,
  NOW() AS ingested_at,
  to_timestamp('{{ var("execution_date") }}') AS updated_at
FROM {{ source('raw', 'trust_report_trust_accounting_report_co')}}