{{
    config(
        materialized='table',
        full_refresh = false,
        post_hook=[
            'ANALYZE TABLE {{ this }} COMPUTE STATISTICS',
        ]
    )
}}

WITH kordev_toggle_updates AS (
    SELECT *
    FROM {{ ref('d_syc_client_migration_segments_co') }}
),

snc_client_loan_calculations_co AS (
--bronze.snc_client_loan_calculations_co
SELECT DISTINCT
    -- MAPPED FIELDS - DIRECT ATTRIBUTES
	sclc.id,
    sclc.applicable_rate,
    sclc.approved_amount,
    sclc.calculation_date,
    sclc.cancellation_reason,
    sclc.client_full_payment,
    sclc.client_id,
    sclc.client_min_payment,
    sclc.current_interest_covered_this_month,
    sclc.current_interest_covered_this_period,
    sclc.current_interest_due_this_period,
    sclc.current_positive_balance,
    sclc.current_principal_covered_this_month,
    sclc.current_principal_covered_this_period,
    sclc.current_principal_due_this_period,
    sclc.days_past_due,
    sclc.effective_annual_rate,
    sclc.expected_chargeoff_rate,
    sclc.first_payment_date,
    sclc.full_payment,
    sclc.initial_installment_amount,
    sclc.interest_on_overdue_principal,
    sclc.interest_on_overdue_principal_covered_this_period,
    sclc.interest_overdue,
    sclc.interest_overdue_covered_this_month,
    sclc.interest_overdue_covered_this_period,
    sclc.ipmt,
    sclc.is_cancelled,
    sclc.is_full_payment,
    sclc.is_fully_paid,
    sclc.is_fully_paid_in_old_loan_tape,
    sclc.loan_id,
    sclc.min_payment,
    sclc.monthly_positive_balance,
    sclc.months_on_books,
    sclc.origination_date,
    sclc.paid_installments,
    cast(sclc.payday as date),
    sclc.positive_balance,
    sclc.ppmt,
    sclc.prepayment_this_period,
    sclc.principal_overdue,
    sclc.principal_overdue_covered_this_month,
    sclc.principal_overdue_covered_this_period,
    sclc.term,
    sclc.total_interest_paid,
    sclc.total_applied_payment,
    sclc.total_principal_paid,
    sclc.unpaid_interest,
    sclc.unpaid_principal,
    sclc.unpaid_principal_covered_this_month,
    sclc.vintage,
    sclc.client_total_payment,
    sclc.period_prepayment_benefit,
    sclc.total_prepayment_benefit,
    sclc.current_installment_amount,
    sclc.accrued_interest_this_month,
    sclc.loan_ownership,
    sclc.prepayment_benefit_this_month,
    sclc.client_total_payment_addi,
    sclc.client_total_payment_pa,
    sclc.condoned_interest_this_month,
    sclc.interest_on_overdue_principal_covered_this_month,
    cast(sclc.client_payday as date),
    sclc.client_delinquency_balance,
    sclc.total_moratory_interest_condoned,
    sclc.total_interest_overdue_condoned,
    sclc.total_principal_overdue_condoned,
    sclc.total_current_interest_condoned,
    sclc.total_current_principal_condoned,
    sclc.total_unpaid_principal_condoned,
    sclc.interest_condoned_in_first_period,
    sclc.low_balance_loan,
    sclc.guarantee_overdue,
    sclc.current_guarantee_due_this_period,
    sclc.unpaid_guarantee,
    sclc.total_guarantee_paid,
    sclc.guarantee_covered_this_period,
    sclc.guarantee_covered_this_month,
    sclc.total_guarantee_condoned,
    sclc.iof_additional_rate,
    sclc.iof_daily_rate,
    sclc.iof_installment_limit_rate,
    sclc.initial_iof_amount,
    sclc.delinquency_iof,
    sclc.total_delinquency_iof_paid,
    sclc.late_fees AS unpaid_collection_fees,
    sclc.total_late_fees_paid AS total_collection_fees_paid, 
    sclc.total_late_fees_condoned AS total_collection_fees_condoned,
    sclc.created_at,
    'lms' as loan_tape_source,
    NOW()::date as ingested_at,
    NOW() as updated_at

-- DBT SOURCE REFERENCE
FROM {{ ref('snc_client_loan_calculations_co') }} sclc
LEFT JOIN kordev_toggle_updates ktu
ON sclc.client_id = ktu.client_id
WHERE ktu.client_id is null
),

kordev_client_loan_calculations_co AS (
SELECT DISTINCT
	lsrs.id,
    CAST(lsrs.applicable_rate AS decimal(19,4)) AS applicable_rate,
    CAST(lsrs.approved_amount AS decimal(19,2)) AS approved_amount,
    CAST(lsrs.calculation_date AS date) AS calculation_date,
    lsrs.cancellation_reason,
    CAST(lsrs.client_full_payment AS decimal(19,2)) AS client_full_payment,
    lsrs.client_id,
    CAST(lsrs.client_min_payment AS decimal(19,4)) AS client_min_payment,
    CAST(lsrs.current_interest_covered_this_month AS decimal(19,2)) AS current_interest_covered_this_month,
    CAST(lsrs.current_interest_covered_this_period AS decimal(19,2)) AS current_interest_covered_this_period,
    CAST(lsrs.current_interest_due_this_period AS decimal(19,2)) AS current_interest_due_this_period,
    CAST(lsrs.current_positive_balance AS decimal(19,2)) AS current_positive_balance,
    CAST(lsrs.current_principal_covered_this_month AS decimal(19,2)) AS current_principal_covered_this_month,
    CAST(lsrs.current_principal_covered_this_period AS decimal(19,2)) AS current_principal_covered_this_period,
    CAST(lsrs.current_principal_due_this_period AS decimal(19,2)) AS current_principal_due_this_period,
    lsrs.days_past_due,
    CAST(lsrs.effective_annual_rate AS decimal(19,4)) AS effective_annual_rate,
    CAST(lsrs.expected_chargeoff_rate AS decimal(19,4)) AS expected_chargeoff_rate,
    CAST(lsrs.first_payment_date AS date) AS first_payment_date,
    CAST(lsrs.full_payment AS decimal(19,2)) AS full_payment,
    CAST(lsrs.initial_installment_amount AS decimal(19,2)) AS initial_installment_amount,
    CAST(lsrs.interest_on_overdue_principal AS decimal(19,2)) AS interest_on_overdue_principal,
    CAST(lsrs.interest_on_overdue_principal_covered_this_period AS decimal(19,2)) AS interest_on_overdue_principal_covered_this_period,
    CAST(lsrs.interest_overdue AS decimal(19,2)) AS interest_overdue,
    CAST(lsrs.interest_overdue_covered_this_month AS decimal(19,2)) AS interest_overdue_covered_this_month,
    CAST(lsrs.interest_overdue_covered_this_period AS decimal(19,2)) AS interest_overdue_covered_this_period,
    CAST(lsrs.ipmt AS decimal(19,2)) AS ipmt,
    lsrs.is_cancelled,
    lsrs.is_full_payment,
    lsrs.is_fully_paid,
    lsrs.is_fully_paid_in_old_loan_tape,
    lsrs.loan_id,
    CAST(lsrs.min_payment AS decimal(19,2)) AS min_payment,
    CAST(lsrs.monthly_positive_balance AS decimal(19,2)) AS monthly_positive_balance,
    lsrs.months_on_books,
    CAST(lsrs.origination_date AS date) AS origination_date,
    lsrs.paid_installments,
    cast(lsrs.payday as date),
    CAST(lsrs.positive_balance AS decimal(19,2)) AS positive_balance,
    CAST(lsrs.ppmt AS decimal(19,2)) AS ppmt,
    CAST(lsrs.prepayment_this_period AS decimal(19,2)) AS prepayment_this_period,
    CAST(lsrs.principal_overdue AS decimal(19,2)) AS principal_overdue,
    CAST(lsrs.principal_overdue_covered_this_month AS decimal(19,2)) AS principal_overdue_covered_this_month,
    CAST(lsrs.principal_overdue_covered_this_period AS decimal(19,2)) AS principal_overdue_covered_this_period,
    lsrs.term,
    CAST(lsrs.total_interest_paid AS decimal(19,2)) AS total_interest_paid,
    CAST(lsrs.total_applied_payment AS decimal(19,2)) AS total_applied_payment,
    CAST(lsrs.total_principal_paid AS decimal(19,2)) AS total_principal_paid,
    CAST(lsrs.unpaid_interest AS decimal(19,2)) AS unpaid_interest,
    CAST(lsrs.unpaid_principal AS decimal(19,2)) AS unpaid_principal,
    CAST(lsrs.unpaid_principal_covered_this_month AS decimal(19,2)) AS unpaid_principal_covered_this_month,
    lsrs.vintage,
    CAST(lsrs.client_total_payment AS decimal(28,6)) AS client_total_payment,
    CAST(lsrs.period_prepayment_benefit AS decimal(28,6)) AS period_prepayment_benefit,
    CAST(lsrs.total_prepayment_benefit AS decimal(28,6)) AS total_prepayment_benefit,
    CAST(lsrs.current_installment_amount AS decimal(28,6)) AS current_installment_amount,
    CAST(lsrs.accrued_interest_this_month AS decimal(19,2)) AS accrued_interest_this_month,  
    lsrs.loan_ownership,
    CAST(lsrs.prepayment_benefit_this_month AS decimal(19,2)) AS prepayment_benefit_this_month,  
    CAST(lsrs.client_total_payment_addi AS decimal(19,2)) AS client_total_payment_addi,  
    CAST(lsrs.client_total_payment_pa AS decimal(19,2)) AS client_total_payment_pa,  
    CAST(lsrs.condoned_interest_this_month AS decimal(19,2)) AS condoned_interest_this_month,  
    CAST(lsrs.interest_on_overdue_principal_covered_this_month AS decimal(19,2)) AS interest_on_overdue_principal_covered_this_month,  
    CAST(lsrs.client_payday AS date) AS client_payday,  -- Cambio a date
    CAST(lsrs.client_delinquency_balance AS decimal(19,2)) AS client_delinquency_balance,  
    CAST(lsrs.total_moratory_interest_condoned AS decimal(19,2)) AS total_moratory_interest_condoned,  
    CAST(lsrs.total_interest_overdue_condoned AS decimal(19,2)) AS total_interest_overdue_condoned,  
    CAST(lsrs.total_principal_overdue_condoned AS decimal(19,2)) AS total_principal_overdue_condoned,  
    CAST(lsrs.total_current_interest_condoned AS decimal(19,2)) AS total_current_interest_condoned,  
    CAST(lsrs.total_current_principal_condoned AS decimal(19,2)) AS total_current_principal_condoned,  
    CAST(lsrs.total_unpaid_principal_condoned AS decimal(19,2)) AS total_unpaid_principal_condoned,  
    CAST(lsrs.interest_condoned_in_first_period AS decimal(19,2)) AS interest_condoned_in_first_period,  
    lsrs.low_balance_loan,
    CAST(lsrs.guarantee_overdue AS decimal(19,2)) AS guarantee_overdue,  
    CAST(lsrs.current_guarantee_due_this_period AS decimal(19,2)) AS current_guarantee_due_this_period,  
    CAST(lsrs.unpaid_guarantee AS decimal(19,2)) AS unpaid_guarantee,  
    CAST(lsrs.total_guarantee_paid AS decimal(19,2)) AS total_guarantee_paid,  
    CAST(lsrs.guarantee_covered_this_period AS decimal(19,2)) AS guarantee_covered_this_period,  
    CAST(lsrs.guarantee_covered_this_month AS decimal(19,2)) AS guarantee_covered_this_month,  
    CAST(lsrs.total_guarantee_condoned AS decimal(19,2)) AS total_guarantee_condoned,  
    CAST(lsrs.iof_additional_rate AS decimal(19,4)) AS iof_additional_rate,
    CAST(lsrs.iof_daily_rate AS decimal(19,4)) AS iof_daily_rate,
    CAST(lsrs.iof_installment_limit_rate AS decimal(19,4)) AS iof_installment_limit_rate,
    CAST(lsrs.initial_iof_amount AS decimal(19,2)) AS initial_iof_amount,  
    CAST(lsrs.delinquency_iof AS decimal(19,2)) AS delinquency_iof,  
    CAST(lsrs.total_delinquency_iof_paid AS decimal(19,2)) AS total_delinquency_iof_paid,  
    CAST(lsrs.unpaid_collection_fees AS decimal(38,18)) AS unpaid_collection_fees,
    CAST(lsrs.total_collection_fees_paid AS decimal(38,18)) AS total_collection_fees_paid,
    CAST(lsrs.total_collection_fees_condoned AS decimal(38,18)) AS total_collection_fees_condoned,
    lsrs.created_at,
    'kordev' as loan_tape_source,
    NOW()::date as ingested_at,
    NOW() as updated_at
-- DBT SOURCE REFERENCE
FROM {{ source('servicing', 'loan_status_report_silver')}} lsrs
INNER JOIN kordev_toggle_updates ktu
ON lsrs.client_id = ktu.client_id
),

final_table AS (

SELECT *
FROM snc_client_loan_calculations_co
UNION ALL
SELECT *
FROM kordev_client_loan_calculations_co

)
SELECT *
FROM final_table;